services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
    entrypoint: >
      sh -c "yarn && exec yarn start"