services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    pull_policy: build
    entrypoint: >
      sh -c "exec yarn run start"
