services:
  # otel-lgtm:
  #   image: grafana/otel-lgtm
  #   container_name: otel_lgtm
  #   ports:
  #     - "4317:4317"  # OpenTelemetery GRPC endpoint
  #     - "4318:4318"  # OpenTelemetry HTTP endpoint
  #     - "3000:3000"  # Grafana UI
  #   env_file:
  #     - .env
  #   restart: unless-stopped
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data/app:/app
    env_file:
      - .env
    restart: unless-stopped
    entrypoint: >
      sh -c "exec yarn start"
    # depends_on:
    #   - otel-lgtm