
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Punishments` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Punishments
 * 
 */
export type PunishmentsModel = runtime.Types.Result.DefaultSelection<Prisma.$PunishmentsPayload>

export type AggregatePunishments = {
  _count: PunishmentsCountAggregateOutputType | null
  _min: PunishmentsMinAggregateOutputType | null
  _max: PunishmentsMaxAggregateOutputType | null
}

export type PunishmentsMinAggregateOutputType = {
  id: string | null
  punishmentType: $Enums.PunishmentType | null
  punishmentReason: string | null
  duration: Date | null
  staffUserId: string | null
  punishedUserId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PunishmentsMaxAggregateOutputType = {
  id: string | null
  punishmentType: $Enums.PunishmentType | null
  punishmentReason: string | null
  duration: Date | null
  staffUserId: string | null
  punishedUserId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PunishmentsCountAggregateOutputType = {
  id: number
  punishmentType: number
  punishmentReason: number
  duration: number
  staffUserId: number
  punishedUserId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PunishmentsMinAggregateInputType = {
  id?: true
  punishmentType?: true
  punishmentReason?: true
  duration?: true
  staffUserId?: true
  punishedUserId?: true
  createdAt?: true
  updatedAt?: true
}

export type PunishmentsMaxAggregateInputType = {
  id?: true
  punishmentType?: true
  punishmentReason?: true
  duration?: true
  staffUserId?: true
  punishedUserId?: true
  createdAt?: true
  updatedAt?: true
}

export type PunishmentsCountAggregateInputType = {
  id?: true
  punishmentType?: true
  punishmentReason?: true
  duration?: true
  staffUserId?: true
  punishedUserId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PunishmentsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Punishments to aggregate.
   */
  where?: Prisma.PunishmentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Punishments to fetch.
   */
  orderBy?: Prisma.PunishmentsOrderByWithRelationInput | Prisma.PunishmentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PunishmentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Punishments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Punishments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Punishments
  **/
  _count?: true | PunishmentsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PunishmentsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PunishmentsMaxAggregateInputType
}

export type GetPunishmentsAggregateType<T extends PunishmentsAggregateArgs> = {
      [P in keyof T & keyof AggregatePunishments]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePunishments[P]>
    : Prisma.GetScalarType<T[P], AggregatePunishments[P]>
}




export type PunishmentsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PunishmentsWhereInput
  orderBy?: Prisma.PunishmentsOrderByWithAggregationInput | Prisma.PunishmentsOrderByWithAggregationInput[]
  by: Prisma.PunishmentsScalarFieldEnum[] | Prisma.PunishmentsScalarFieldEnum
  having?: Prisma.PunishmentsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PunishmentsCountAggregateInputType | true
  _min?: PunishmentsMinAggregateInputType
  _max?: PunishmentsMaxAggregateInputType
}

export type PunishmentsGroupByOutputType = {
  id: string
  punishmentType: $Enums.PunishmentType
  punishmentReason: string
  duration: Date
  staffUserId: string
  punishedUserId: string
  createdAt: Date
  updatedAt: Date
  _count: PunishmentsCountAggregateOutputType | null
  _min: PunishmentsMinAggregateOutputType | null
  _max: PunishmentsMaxAggregateOutputType | null
}

export type GetPunishmentsGroupByPayload<T extends PunishmentsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PunishmentsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PunishmentsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PunishmentsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PunishmentsGroupByOutputType[P]>
      }
    >
  >



export type PunishmentsWhereInput = {
  AND?: Prisma.PunishmentsWhereInput | Prisma.PunishmentsWhereInput[]
  OR?: Prisma.PunishmentsWhereInput[]
  NOT?: Prisma.PunishmentsWhereInput | Prisma.PunishmentsWhereInput[]
  id?: Prisma.StringFilter<"Punishments"> | string
  punishmentType?: Prisma.EnumPunishmentTypeFilter<"Punishments"> | $Enums.PunishmentType
  punishmentReason?: Prisma.StringFilter<"Punishments"> | string
  duration?: Prisma.DateTimeFilter<"Punishments"> | Date | string
  staffUserId?: Prisma.StringFilter<"Punishments"> | string
  punishedUserId?: Prisma.StringFilter<"Punishments"> | string
  createdAt?: Prisma.DateTimeFilter<"Punishments"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Punishments"> | Date | string
  staffUser?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  punishedUser?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type PunishmentsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  punishmentType?: Prisma.SortOrder
  punishmentReason?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  staffUserId?: Prisma.SortOrder
  punishedUserId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  staffUser?: Prisma.UserOrderByWithRelationInput
  punishedUser?: Prisma.UserOrderByWithRelationInput
}

export type PunishmentsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PunishmentsWhereInput | Prisma.PunishmentsWhereInput[]
  OR?: Prisma.PunishmentsWhereInput[]
  NOT?: Prisma.PunishmentsWhereInput | Prisma.PunishmentsWhereInput[]
  punishmentType?: Prisma.EnumPunishmentTypeFilter<"Punishments"> | $Enums.PunishmentType
  punishmentReason?: Prisma.StringFilter<"Punishments"> | string
  duration?: Prisma.DateTimeFilter<"Punishments"> | Date | string
  staffUserId?: Prisma.StringFilter<"Punishments"> | string
  punishedUserId?: Prisma.StringFilter<"Punishments"> | string
  createdAt?: Prisma.DateTimeFilter<"Punishments"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Punishments"> | Date | string
  staffUser?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  punishedUser?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type PunishmentsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  punishmentType?: Prisma.SortOrder
  punishmentReason?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  staffUserId?: Prisma.SortOrder
  punishedUserId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PunishmentsCountOrderByAggregateInput
  _max?: Prisma.PunishmentsMaxOrderByAggregateInput
  _min?: Prisma.PunishmentsMinOrderByAggregateInput
}

export type PunishmentsScalarWhereWithAggregatesInput = {
  AND?: Prisma.PunishmentsScalarWhereWithAggregatesInput | Prisma.PunishmentsScalarWhereWithAggregatesInput[]
  OR?: Prisma.PunishmentsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PunishmentsScalarWhereWithAggregatesInput | Prisma.PunishmentsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Punishments"> | string
  punishmentType?: Prisma.EnumPunishmentTypeWithAggregatesFilter<"Punishments"> | $Enums.PunishmentType
  punishmentReason?: Prisma.StringWithAggregatesFilter<"Punishments"> | string
  duration?: Prisma.DateTimeWithAggregatesFilter<"Punishments"> | Date | string
  staffUserId?: Prisma.StringWithAggregatesFilter<"Punishments"> | string
  punishedUserId?: Prisma.StringWithAggregatesFilter<"Punishments"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Punishments"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Punishments"> | Date | string
}

export type PunishmentsCreateInput = {
  id?: string
  punishmentType: $Enums.PunishmentType
  punishmentReason: string
  duration: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  staffUser: Prisma.UserCreateNestedOneWithoutIssuedPunishmentsInput
  punishedUser: Prisma.UserCreateNestedOneWithoutReceivedPunishmentsInput
}

export type PunishmentsUncheckedCreateInput = {
  id?: string
  punishmentType: $Enums.PunishmentType
  punishmentReason: string
  duration: Date | string
  staffUserId: string
  punishedUserId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PunishmentsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  punishmentType?: Prisma.EnumPunishmentTypeFieldUpdateOperationsInput | $Enums.PunishmentType
  punishmentReason?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  staffUser?: Prisma.UserUpdateOneRequiredWithoutIssuedPunishmentsNestedInput
  punishedUser?: Prisma.UserUpdateOneRequiredWithoutReceivedPunishmentsNestedInput
}

export type PunishmentsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  punishmentType?: Prisma.EnumPunishmentTypeFieldUpdateOperationsInput | $Enums.PunishmentType
  punishmentReason?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  staffUserId?: Prisma.StringFieldUpdateOperationsInput | string
  punishedUserId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PunishmentsCreateManyInput = {
  id?: string
  punishmentType: $Enums.PunishmentType
  punishmentReason: string
  duration: Date | string
  staffUserId: string
  punishedUserId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PunishmentsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  punishmentType?: Prisma.EnumPunishmentTypeFieldUpdateOperationsInput | $Enums.PunishmentType
  punishmentReason?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PunishmentsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  punishmentType?: Prisma.EnumPunishmentTypeFieldUpdateOperationsInput | $Enums.PunishmentType
  punishmentReason?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  staffUserId?: Prisma.StringFieldUpdateOperationsInput | string
  punishedUserId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PunishmentsListRelationFilter = {
  every?: Prisma.PunishmentsWhereInput
  some?: Prisma.PunishmentsWhereInput
  none?: Prisma.PunishmentsWhereInput
}

export type PunishmentsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PunishmentsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  punishmentType?: Prisma.SortOrder
  punishmentReason?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  staffUserId?: Prisma.SortOrder
  punishedUserId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PunishmentsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  punishmentType?: Prisma.SortOrder
  punishmentReason?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  staffUserId?: Prisma.SortOrder
  punishedUserId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PunishmentsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  punishmentType?: Prisma.SortOrder
  punishmentReason?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  staffUserId?: Prisma.SortOrder
  punishedUserId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PunishmentsCreateNestedManyWithoutStaffUserInput = {
  create?: Prisma.XOR<Prisma.PunishmentsCreateWithoutStaffUserInput, Prisma.PunishmentsUncheckedCreateWithoutStaffUserInput> | Prisma.PunishmentsCreateWithoutStaffUserInput[] | Prisma.PunishmentsUncheckedCreateWithoutStaffUserInput[]
  connectOrCreate?: Prisma.PunishmentsCreateOrConnectWithoutStaffUserInput | Prisma.PunishmentsCreateOrConnectWithoutStaffUserInput[]
  createMany?: Prisma.PunishmentsCreateManyStaffUserInputEnvelope
  connect?: Prisma.PunishmentsWhereUniqueInput | Prisma.PunishmentsWhereUniqueInput[]
}

export type PunishmentsCreateNestedManyWithoutPunishedUserInput = {
  create?: Prisma.XOR<Prisma.PunishmentsCreateWithoutPunishedUserInput, Prisma.PunishmentsUncheckedCreateWithoutPunishedUserInput> | Prisma.PunishmentsCreateWithoutPunishedUserInput[] | Prisma.PunishmentsUncheckedCreateWithoutPunishedUserInput[]
  connectOrCreate?: Prisma.PunishmentsCreateOrConnectWithoutPunishedUserInput | Prisma.PunishmentsCreateOrConnectWithoutPunishedUserInput[]
  createMany?: Prisma.PunishmentsCreateManyPunishedUserInputEnvelope
  connect?: Prisma.PunishmentsWhereUniqueInput | Prisma.PunishmentsWhereUniqueInput[]
}

export type PunishmentsUncheckedCreateNestedManyWithoutStaffUserInput = {
  create?: Prisma.XOR<Prisma.PunishmentsCreateWithoutStaffUserInput, Prisma.PunishmentsUncheckedCreateWithoutStaffUserInput> | Prisma.PunishmentsCreateWithoutStaffUserInput[] | Prisma.PunishmentsUncheckedCreateWithoutStaffUserInput[]
  connectOrCreate?: Prisma.PunishmentsCreateOrConnectWithoutStaffUserInput | Prisma.PunishmentsCreateOrConnectWithoutStaffUserInput[]
  createMany?: Prisma.PunishmentsCreateManyStaffUserInputEnvelope
  connect?: Prisma.PunishmentsWhereUniqueInput | Prisma.PunishmentsWhereUniqueInput[]
}

export type PunishmentsUncheckedCreateNestedManyWithoutPunishedUserInput = {
  create?: Prisma.XOR<Prisma.PunishmentsCreateWithoutPunishedUserInput, Prisma.PunishmentsUncheckedCreateWithoutPunishedUserInput> | Prisma.PunishmentsCreateWithoutPunishedUserInput[] | Prisma.PunishmentsUncheckedCreateWithoutPunishedUserInput[]
  connectOrCreate?: Prisma.PunishmentsCreateOrConnectWithoutPunishedUserInput | Prisma.PunishmentsCreateOrConnectWithoutPunishedUserInput[]
  createMany?: Prisma.PunishmentsCreateManyPunishedUserInputEnvelope
  connect?: Prisma.PunishmentsWhereUniqueInput | Prisma.PunishmentsWhereUniqueInput[]
}

export type PunishmentsUpdateManyWithoutStaffUserNestedInput = {
  create?: Prisma.XOR<Prisma.PunishmentsCreateWithoutStaffUserInput, Prisma.PunishmentsUncheckedCreateWithoutStaffUserInput> | Prisma.PunishmentsCreateWithoutStaffUserInput[] | Prisma.PunishmentsUncheckedCreateWithoutStaffUserInput[]
  connectOrCreate?: Prisma.PunishmentsCreateOrConnectWithoutStaffUserInput | Prisma.PunishmentsCreateOrConnectWithoutStaffUserInput[]
  upsert?: Prisma.PunishmentsUpsertWithWhereUniqueWithoutStaffUserInput | Prisma.PunishmentsUpsertWithWhereUniqueWithoutStaffUserInput[]
  createMany?: Prisma.PunishmentsCreateManyStaffUserInputEnvelope
  set?: Prisma.PunishmentsWhereUniqueInput | Prisma.PunishmentsWhereUniqueInput[]
  disconnect?: Prisma.PunishmentsWhereUniqueInput | Prisma.PunishmentsWhereUniqueInput[]
  delete?: Prisma.PunishmentsWhereUniqueInput | Prisma.PunishmentsWhereUniqueInput[]
  connect?: Prisma.PunishmentsWhereUniqueInput | Prisma.PunishmentsWhereUniqueInput[]
  update?: Prisma.PunishmentsUpdateWithWhereUniqueWithoutStaffUserInput | Prisma.PunishmentsUpdateWithWhereUniqueWithoutStaffUserInput[]
  updateMany?: Prisma.PunishmentsUpdateManyWithWhereWithoutStaffUserInput | Prisma.PunishmentsUpdateManyWithWhereWithoutStaffUserInput[]
  deleteMany?: Prisma.PunishmentsScalarWhereInput | Prisma.PunishmentsScalarWhereInput[]
}

export type PunishmentsUpdateManyWithoutPunishedUserNestedInput = {
  create?: Prisma.XOR<Prisma.PunishmentsCreateWithoutPunishedUserInput, Prisma.PunishmentsUncheckedCreateWithoutPunishedUserInput> | Prisma.PunishmentsCreateWithoutPunishedUserInput[] | Prisma.PunishmentsUncheckedCreateWithoutPunishedUserInput[]
  connectOrCreate?: Prisma.PunishmentsCreateOrConnectWithoutPunishedUserInput | Prisma.PunishmentsCreateOrConnectWithoutPunishedUserInput[]
  upsert?: Prisma.PunishmentsUpsertWithWhereUniqueWithoutPunishedUserInput | Prisma.PunishmentsUpsertWithWhereUniqueWithoutPunishedUserInput[]
  createMany?: Prisma.PunishmentsCreateManyPunishedUserInputEnvelope
  set?: Prisma.PunishmentsWhereUniqueInput | Prisma.PunishmentsWhereUniqueInput[]
  disconnect?: Prisma.PunishmentsWhereUniqueInput | Prisma.PunishmentsWhereUniqueInput[]
  delete?: Prisma.PunishmentsWhereUniqueInput | Prisma.PunishmentsWhereUniqueInput[]
  connect?: Prisma.PunishmentsWhereUniqueInput | Prisma.PunishmentsWhereUniqueInput[]
  update?: Prisma.PunishmentsUpdateWithWhereUniqueWithoutPunishedUserInput | Prisma.PunishmentsUpdateWithWhereUniqueWithoutPunishedUserInput[]
  updateMany?: Prisma.PunishmentsUpdateManyWithWhereWithoutPunishedUserInput | Prisma.PunishmentsUpdateManyWithWhereWithoutPunishedUserInput[]
  deleteMany?: Prisma.PunishmentsScalarWhereInput | Prisma.PunishmentsScalarWhereInput[]
}

export type PunishmentsUncheckedUpdateManyWithoutStaffUserNestedInput = {
  create?: Prisma.XOR<Prisma.PunishmentsCreateWithoutStaffUserInput, Prisma.PunishmentsUncheckedCreateWithoutStaffUserInput> | Prisma.PunishmentsCreateWithoutStaffUserInput[] | Prisma.PunishmentsUncheckedCreateWithoutStaffUserInput[]
  connectOrCreate?: Prisma.PunishmentsCreateOrConnectWithoutStaffUserInput | Prisma.PunishmentsCreateOrConnectWithoutStaffUserInput[]
  upsert?: Prisma.PunishmentsUpsertWithWhereUniqueWithoutStaffUserInput | Prisma.PunishmentsUpsertWithWhereUniqueWithoutStaffUserInput[]
  createMany?: Prisma.PunishmentsCreateManyStaffUserInputEnvelope
  set?: Prisma.PunishmentsWhereUniqueInput | Prisma.PunishmentsWhereUniqueInput[]
  disconnect?: Prisma.PunishmentsWhereUniqueInput | Prisma.PunishmentsWhereUniqueInput[]
  delete?: Prisma.PunishmentsWhereUniqueInput | Prisma.PunishmentsWhereUniqueInput[]
  connect?: Prisma.PunishmentsWhereUniqueInput | Prisma.PunishmentsWhereUniqueInput[]
  update?: Prisma.PunishmentsUpdateWithWhereUniqueWithoutStaffUserInput | Prisma.PunishmentsUpdateWithWhereUniqueWithoutStaffUserInput[]
  updateMany?: Prisma.PunishmentsUpdateManyWithWhereWithoutStaffUserInput | Prisma.PunishmentsUpdateManyWithWhereWithoutStaffUserInput[]
  deleteMany?: Prisma.PunishmentsScalarWhereInput | Prisma.PunishmentsScalarWhereInput[]
}

export type PunishmentsUncheckedUpdateManyWithoutPunishedUserNestedInput = {
  create?: Prisma.XOR<Prisma.PunishmentsCreateWithoutPunishedUserInput, Prisma.PunishmentsUncheckedCreateWithoutPunishedUserInput> | Prisma.PunishmentsCreateWithoutPunishedUserInput[] | Prisma.PunishmentsUncheckedCreateWithoutPunishedUserInput[]
  connectOrCreate?: Prisma.PunishmentsCreateOrConnectWithoutPunishedUserInput | Prisma.PunishmentsCreateOrConnectWithoutPunishedUserInput[]
  upsert?: Prisma.PunishmentsUpsertWithWhereUniqueWithoutPunishedUserInput | Prisma.PunishmentsUpsertWithWhereUniqueWithoutPunishedUserInput[]
  createMany?: Prisma.PunishmentsCreateManyPunishedUserInputEnvelope
  set?: Prisma.PunishmentsWhereUniqueInput | Prisma.PunishmentsWhereUniqueInput[]
  disconnect?: Prisma.PunishmentsWhereUniqueInput | Prisma.PunishmentsWhereUniqueInput[]
  delete?: Prisma.PunishmentsWhereUniqueInput | Prisma.PunishmentsWhereUniqueInput[]
  connect?: Prisma.PunishmentsWhereUniqueInput | Prisma.PunishmentsWhereUniqueInput[]
  update?: Prisma.PunishmentsUpdateWithWhereUniqueWithoutPunishedUserInput | Prisma.PunishmentsUpdateWithWhereUniqueWithoutPunishedUserInput[]
  updateMany?: Prisma.PunishmentsUpdateManyWithWhereWithoutPunishedUserInput | Prisma.PunishmentsUpdateManyWithWhereWithoutPunishedUserInput[]
  deleteMany?: Prisma.PunishmentsScalarWhereInput | Prisma.PunishmentsScalarWhereInput[]
}

export type EnumPunishmentTypeFieldUpdateOperationsInput = {
  set?: $Enums.PunishmentType
}

export type PunishmentsCreateWithoutStaffUserInput = {
  id?: string
  punishmentType: $Enums.PunishmentType
  punishmentReason: string
  duration: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  punishedUser: Prisma.UserCreateNestedOneWithoutReceivedPunishmentsInput
}

export type PunishmentsUncheckedCreateWithoutStaffUserInput = {
  id?: string
  punishmentType: $Enums.PunishmentType
  punishmentReason: string
  duration: Date | string
  punishedUserId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PunishmentsCreateOrConnectWithoutStaffUserInput = {
  where: Prisma.PunishmentsWhereUniqueInput
  create: Prisma.XOR<Prisma.PunishmentsCreateWithoutStaffUserInput, Prisma.PunishmentsUncheckedCreateWithoutStaffUserInput>
}

export type PunishmentsCreateManyStaffUserInputEnvelope = {
  data: Prisma.PunishmentsCreateManyStaffUserInput | Prisma.PunishmentsCreateManyStaffUserInput[]
  skipDuplicates?: boolean
}

export type PunishmentsCreateWithoutPunishedUserInput = {
  id?: string
  punishmentType: $Enums.PunishmentType
  punishmentReason: string
  duration: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  staffUser: Prisma.UserCreateNestedOneWithoutIssuedPunishmentsInput
}

export type PunishmentsUncheckedCreateWithoutPunishedUserInput = {
  id?: string
  punishmentType: $Enums.PunishmentType
  punishmentReason: string
  duration: Date | string
  staffUserId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PunishmentsCreateOrConnectWithoutPunishedUserInput = {
  where: Prisma.PunishmentsWhereUniqueInput
  create: Prisma.XOR<Prisma.PunishmentsCreateWithoutPunishedUserInput, Prisma.PunishmentsUncheckedCreateWithoutPunishedUserInput>
}

export type PunishmentsCreateManyPunishedUserInputEnvelope = {
  data: Prisma.PunishmentsCreateManyPunishedUserInput | Prisma.PunishmentsCreateManyPunishedUserInput[]
  skipDuplicates?: boolean
}

export type PunishmentsUpsertWithWhereUniqueWithoutStaffUserInput = {
  where: Prisma.PunishmentsWhereUniqueInput
  update: Prisma.XOR<Prisma.PunishmentsUpdateWithoutStaffUserInput, Prisma.PunishmentsUncheckedUpdateWithoutStaffUserInput>
  create: Prisma.XOR<Prisma.PunishmentsCreateWithoutStaffUserInput, Prisma.PunishmentsUncheckedCreateWithoutStaffUserInput>
}

export type PunishmentsUpdateWithWhereUniqueWithoutStaffUserInput = {
  where: Prisma.PunishmentsWhereUniqueInput
  data: Prisma.XOR<Prisma.PunishmentsUpdateWithoutStaffUserInput, Prisma.PunishmentsUncheckedUpdateWithoutStaffUserInput>
}

export type PunishmentsUpdateManyWithWhereWithoutStaffUserInput = {
  where: Prisma.PunishmentsScalarWhereInput
  data: Prisma.XOR<Prisma.PunishmentsUpdateManyMutationInput, Prisma.PunishmentsUncheckedUpdateManyWithoutStaffUserInput>
}

export type PunishmentsScalarWhereInput = {
  AND?: Prisma.PunishmentsScalarWhereInput | Prisma.PunishmentsScalarWhereInput[]
  OR?: Prisma.PunishmentsScalarWhereInput[]
  NOT?: Prisma.PunishmentsScalarWhereInput | Prisma.PunishmentsScalarWhereInput[]
  id?: Prisma.StringFilter<"Punishments"> | string
  punishmentType?: Prisma.EnumPunishmentTypeFilter<"Punishments"> | $Enums.PunishmentType
  punishmentReason?: Prisma.StringFilter<"Punishments"> | string
  duration?: Prisma.DateTimeFilter<"Punishments"> | Date | string
  staffUserId?: Prisma.StringFilter<"Punishments"> | string
  punishedUserId?: Prisma.StringFilter<"Punishments"> | string
  createdAt?: Prisma.DateTimeFilter<"Punishments"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Punishments"> | Date | string
}

export type PunishmentsUpsertWithWhereUniqueWithoutPunishedUserInput = {
  where: Prisma.PunishmentsWhereUniqueInput
  update: Prisma.XOR<Prisma.PunishmentsUpdateWithoutPunishedUserInput, Prisma.PunishmentsUncheckedUpdateWithoutPunishedUserInput>
  create: Prisma.XOR<Prisma.PunishmentsCreateWithoutPunishedUserInput, Prisma.PunishmentsUncheckedCreateWithoutPunishedUserInput>
}

export type PunishmentsUpdateWithWhereUniqueWithoutPunishedUserInput = {
  where: Prisma.PunishmentsWhereUniqueInput
  data: Prisma.XOR<Prisma.PunishmentsUpdateWithoutPunishedUserInput, Prisma.PunishmentsUncheckedUpdateWithoutPunishedUserInput>
}

export type PunishmentsUpdateManyWithWhereWithoutPunishedUserInput = {
  where: Prisma.PunishmentsScalarWhereInput
  data: Prisma.XOR<Prisma.PunishmentsUpdateManyMutationInput, Prisma.PunishmentsUncheckedUpdateManyWithoutPunishedUserInput>
}

export type PunishmentsCreateManyStaffUserInput = {
  id?: string
  punishmentType: $Enums.PunishmentType
  punishmentReason: string
  duration: Date | string
  punishedUserId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PunishmentsCreateManyPunishedUserInput = {
  id?: string
  punishmentType: $Enums.PunishmentType
  punishmentReason: string
  duration: Date | string
  staffUserId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PunishmentsUpdateWithoutStaffUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  punishmentType?: Prisma.EnumPunishmentTypeFieldUpdateOperationsInput | $Enums.PunishmentType
  punishmentReason?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  punishedUser?: Prisma.UserUpdateOneRequiredWithoutReceivedPunishmentsNestedInput
}

export type PunishmentsUncheckedUpdateWithoutStaffUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  punishmentType?: Prisma.EnumPunishmentTypeFieldUpdateOperationsInput | $Enums.PunishmentType
  punishmentReason?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  punishedUserId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PunishmentsUncheckedUpdateManyWithoutStaffUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  punishmentType?: Prisma.EnumPunishmentTypeFieldUpdateOperationsInput | $Enums.PunishmentType
  punishmentReason?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  punishedUserId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PunishmentsUpdateWithoutPunishedUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  punishmentType?: Prisma.EnumPunishmentTypeFieldUpdateOperationsInput | $Enums.PunishmentType
  punishmentReason?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  staffUser?: Prisma.UserUpdateOneRequiredWithoutIssuedPunishmentsNestedInput
}

export type PunishmentsUncheckedUpdateWithoutPunishedUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  punishmentType?: Prisma.EnumPunishmentTypeFieldUpdateOperationsInput | $Enums.PunishmentType
  punishmentReason?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  staffUserId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PunishmentsUncheckedUpdateManyWithoutPunishedUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  punishmentType?: Prisma.EnumPunishmentTypeFieldUpdateOperationsInput | $Enums.PunishmentType
  punishmentReason?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  staffUserId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PunishmentsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  punishmentType?: boolean
  punishmentReason?: boolean
  duration?: boolean
  staffUserId?: boolean
  punishedUserId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  staffUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  punishedUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["punishments"]>

export type PunishmentsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  punishmentType?: boolean
  punishmentReason?: boolean
  duration?: boolean
  staffUserId?: boolean
  punishedUserId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  staffUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  punishedUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["punishments"]>

export type PunishmentsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  punishmentType?: boolean
  punishmentReason?: boolean
  duration?: boolean
  staffUserId?: boolean
  punishedUserId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  staffUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  punishedUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["punishments"]>

export type PunishmentsSelectScalar = {
  id?: boolean
  punishmentType?: boolean
  punishmentReason?: boolean
  duration?: boolean
  staffUserId?: boolean
  punishedUserId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PunishmentsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "punishmentType" | "punishmentReason" | "duration" | "staffUserId" | "punishedUserId" | "createdAt" | "updatedAt", ExtArgs["result"]["punishments"]>
export type PunishmentsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  staffUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  punishedUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type PunishmentsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  staffUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  punishedUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type PunishmentsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  staffUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  punishedUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $PunishmentsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Punishments"
  objects: {
    staffUser: Prisma.$UserPayload<ExtArgs>
    punishedUser: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    punishmentType: $Enums.PunishmentType
    punishmentReason: string
    duration: Date
    staffUserId: string
    punishedUserId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["punishments"]>
  composites: {}
}

export type PunishmentsGetPayload<S extends boolean | null | undefined | PunishmentsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PunishmentsPayload, S>

export type PunishmentsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PunishmentsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PunishmentsCountAggregateInputType | true
  }

export interface PunishmentsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Punishments'], meta: { name: 'Punishments' } }
  /**
   * Find zero or one Punishments that matches the filter.
   * @param {PunishmentsFindUniqueArgs} args - Arguments to find a Punishments
   * @example
   * // Get one Punishments
   * const punishments = await prisma.punishments.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PunishmentsFindUniqueArgs>(args: Prisma.SelectSubset<T, PunishmentsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PunishmentsClient<runtime.Types.Result.GetResult<Prisma.$PunishmentsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Punishments that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PunishmentsFindUniqueOrThrowArgs} args - Arguments to find a Punishments
   * @example
   * // Get one Punishments
   * const punishments = await prisma.punishments.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PunishmentsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PunishmentsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PunishmentsClient<runtime.Types.Result.GetResult<Prisma.$PunishmentsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Punishments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PunishmentsFindFirstArgs} args - Arguments to find a Punishments
   * @example
   * // Get one Punishments
   * const punishments = await prisma.punishments.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PunishmentsFindFirstArgs>(args?: Prisma.SelectSubset<T, PunishmentsFindFirstArgs<ExtArgs>>): Prisma.Prisma__PunishmentsClient<runtime.Types.Result.GetResult<Prisma.$PunishmentsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Punishments that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PunishmentsFindFirstOrThrowArgs} args - Arguments to find a Punishments
   * @example
   * // Get one Punishments
   * const punishments = await prisma.punishments.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PunishmentsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PunishmentsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PunishmentsClient<runtime.Types.Result.GetResult<Prisma.$PunishmentsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Punishments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PunishmentsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Punishments
   * const punishments = await prisma.punishments.findMany()
   * 
   * // Get first 10 Punishments
   * const punishments = await prisma.punishments.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const punishmentsWithIdOnly = await prisma.punishments.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PunishmentsFindManyArgs>(args?: Prisma.SelectSubset<T, PunishmentsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PunishmentsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Punishments.
   * @param {PunishmentsCreateArgs} args - Arguments to create a Punishments.
   * @example
   * // Create one Punishments
   * const Punishments = await prisma.punishments.create({
   *   data: {
   *     // ... data to create a Punishments
   *   }
   * })
   * 
   */
  create<T extends PunishmentsCreateArgs>(args: Prisma.SelectSubset<T, PunishmentsCreateArgs<ExtArgs>>): Prisma.Prisma__PunishmentsClient<runtime.Types.Result.GetResult<Prisma.$PunishmentsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Punishments.
   * @param {PunishmentsCreateManyArgs} args - Arguments to create many Punishments.
   * @example
   * // Create many Punishments
   * const punishments = await prisma.punishments.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PunishmentsCreateManyArgs>(args?: Prisma.SelectSubset<T, PunishmentsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Punishments and returns the data saved in the database.
   * @param {PunishmentsCreateManyAndReturnArgs} args - Arguments to create many Punishments.
   * @example
   * // Create many Punishments
   * const punishments = await prisma.punishments.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Punishments and only return the `id`
   * const punishmentsWithIdOnly = await prisma.punishments.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PunishmentsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PunishmentsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PunishmentsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Punishments.
   * @param {PunishmentsDeleteArgs} args - Arguments to delete one Punishments.
   * @example
   * // Delete one Punishments
   * const Punishments = await prisma.punishments.delete({
   *   where: {
   *     // ... filter to delete one Punishments
   *   }
   * })
   * 
   */
  delete<T extends PunishmentsDeleteArgs>(args: Prisma.SelectSubset<T, PunishmentsDeleteArgs<ExtArgs>>): Prisma.Prisma__PunishmentsClient<runtime.Types.Result.GetResult<Prisma.$PunishmentsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Punishments.
   * @param {PunishmentsUpdateArgs} args - Arguments to update one Punishments.
   * @example
   * // Update one Punishments
   * const punishments = await prisma.punishments.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PunishmentsUpdateArgs>(args: Prisma.SelectSubset<T, PunishmentsUpdateArgs<ExtArgs>>): Prisma.Prisma__PunishmentsClient<runtime.Types.Result.GetResult<Prisma.$PunishmentsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Punishments.
   * @param {PunishmentsDeleteManyArgs} args - Arguments to filter Punishments to delete.
   * @example
   * // Delete a few Punishments
   * const { count } = await prisma.punishments.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PunishmentsDeleteManyArgs>(args?: Prisma.SelectSubset<T, PunishmentsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Punishments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PunishmentsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Punishments
   * const punishments = await prisma.punishments.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PunishmentsUpdateManyArgs>(args: Prisma.SelectSubset<T, PunishmentsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Punishments and returns the data updated in the database.
   * @param {PunishmentsUpdateManyAndReturnArgs} args - Arguments to update many Punishments.
   * @example
   * // Update many Punishments
   * const punishments = await prisma.punishments.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Punishments and only return the `id`
   * const punishmentsWithIdOnly = await prisma.punishments.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PunishmentsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PunishmentsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PunishmentsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Punishments.
   * @param {PunishmentsUpsertArgs} args - Arguments to update or create a Punishments.
   * @example
   * // Update or create a Punishments
   * const punishments = await prisma.punishments.upsert({
   *   create: {
   *     // ... data to create a Punishments
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Punishments we want to update
   *   }
   * })
   */
  upsert<T extends PunishmentsUpsertArgs>(args: Prisma.SelectSubset<T, PunishmentsUpsertArgs<ExtArgs>>): Prisma.Prisma__PunishmentsClient<runtime.Types.Result.GetResult<Prisma.$PunishmentsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Punishments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PunishmentsCountArgs} args - Arguments to filter Punishments to count.
   * @example
   * // Count the number of Punishments
   * const count = await prisma.punishments.count({
   *   where: {
   *     // ... the filter for the Punishments we want to count
   *   }
   * })
  **/
  count<T extends PunishmentsCountArgs>(
    args?: Prisma.Subset<T, PunishmentsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PunishmentsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Punishments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PunishmentsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PunishmentsAggregateArgs>(args: Prisma.Subset<T, PunishmentsAggregateArgs>): Prisma.PrismaPromise<GetPunishmentsAggregateType<T>>

  /**
   * Group by Punishments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PunishmentsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PunishmentsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PunishmentsGroupByArgs['orderBy'] }
      : { orderBy?: PunishmentsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PunishmentsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPunishmentsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Punishments model
 */
readonly fields: PunishmentsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Punishments.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PunishmentsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  staffUser<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  punishedUser<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Punishments model
 */
export interface PunishmentsFieldRefs {
  readonly id: Prisma.FieldRef<"Punishments", 'String'>
  readonly punishmentType: Prisma.FieldRef<"Punishments", 'PunishmentType'>
  readonly punishmentReason: Prisma.FieldRef<"Punishments", 'String'>
  readonly duration: Prisma.FieldRef<"Punishments", 'DateTime'>
  readonly staffUserId: Prisma.FieldRef<"Punishments", 'String'>
  readonly punishedUserId: Prisma.FieldRef<"Punishments", 'String'>
  readonly createdAt: Prisma.FieldRef<"Punishments", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Punishments", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Punishments findUnique
 */
export type PunishmentsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Punishments
   */
  select?: Prisma.PunishmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Punishments
   */
  omit?: Prisma.PunishmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PunishmentsInclude<ExtArgs> | null
  /**
   * Filter, which Punishments to fetch.
   */
  where: Prisma.PunishmentsWhereUniqueInput
}

/**
 * Punishments findUniqueOrThrow
 */
export type PunishmentsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Punishments
   */
  select?: Prisma.PunishmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Punishments
   */
  omit?: Prisma.PunishmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PunishmentsInclude<ExtArgs> | null
  /**
   * Filter, which Punishments to fetch.
   */
  where: Prisma.PunishmentsWhereUniqueInput
}

/**
 * Punishments findFirst
 */
export type PunishmentsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Punishments
   */
  select?: Prisma.PunishmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Punishments
   */
  omit?: Prisma.PunishmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PunishmentsInclude<ExtArgs> | null
  /**
   * Filter, which Punishments to fetch.
   */
  where?: Prisma.PunishmentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Punishments to fetch.
   */
  orderBy?: Prisma.PunishmentsOrderByWithRelationInput | Prisma.PunishmentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Punishments.
   */
  cursor?: Prisma.PunishmentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Punishments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Punishments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Punishments.
   */
  distinct?: Prisma.PunishmentsScalarFieldEnum | Prisma.PunishmentsScalarFieldEnum[]
}

/**
 * Punishments findFirstOrThrow
 */
export type PunishmentsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Punishments
   */
  select?: Prisma.PunishmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Punishments
   */
  omit?: Prisma.PunishmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PunishmentsInclude<ExtArgs> | null
  /**
   * Filter, which Punishments to fetch.
   */
  where?: Prisma.PunishmentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Punishments to fetch.
   */
  orderBy?: Prisma.PunishmentsOrderByWithRelationInput | Prisma.PunishmentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Punishments.
   */
  cursor?: Prisma.PunishmentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Punishments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Punishments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Punishments.
   */
  distinct?: Prisma.PunishmentsScalarFieldEnum | Prisma.PunishmentsScalarFieldEnum[]
}

/**
 * Punishments findMany
 */
export type PunishmentsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Punishments
   */
  select?: Prisma.PunishmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Punishments
   */
  omit?: Prisma.PunishmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PunishmentsInclude<ExtArgs> | null
  /**
   * Filter, which Punishments to fetch.
   */
  where?: Prisma.PunishmentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Punishments to fetch.
   */
  orderBy?: Prisma.PunishmentsOrderByWithRelationInput | Prisma.PunishmentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Punishments.
   */
  cursor?: Prisma.PunishmentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Punishments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Punishments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Punishments.
   */
  distinct?: Prisma.PunishmentsScalarFieldEnum | Prisma.PunishmentsScalarFieldEnum[]
}

/**
 * Punishments create
 */
export type PunishmentsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Punishments
   */
  select?: Prisma.PunishmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Punishments
   */
  omit?: Prisma.PunishmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PunishmentsInclude<ExtArgs> | null
  /**
   * The data needed to create a Punishments.
   */
  data: Prisma.XOR<Prisma.PunishmentsCreateInput, Prisma.PunishmentsUncheckedCreateInput>
}

/**
 * Punishments createMany
 */
export type PunishmentsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Punishments.
   */
  data: Prisma.PunishmentsCreateManyInput | Prisma.PunishmentsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Punishments createManyAndReturn
 */
export type PunishmentsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Punishments
   */
  select?: Prisma.PunishmentsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Punishments
   */
  omit?: Prisma.PunishmentsOmit<ExtArgs> | null
  /**
   * The data used to create many Punishments.
   */
  data: Prisma.PunishmentsCreateManyInput | Prisma.PunishmentsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PunishmentsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Punishments update
 */
export type PunishmentsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Punishments
   */
  select?: Prisma.PunishmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Punishments
   */
  omit?: Prisma.PunishmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PunishmentsInclude<ExtArgs> | null
  /**
   * The data needed to update a Punishments.
   */
  data: Prisma.XOR<Prisma.PunishmentsUpdateInput, Prisma.PunishmentsUncheckedUpdateInput>
  /**
   * Choose, which Punishments to update.
   */
  where: Prisma.PunishmentsWhereUniqueInput
}

/**
 * Punishments updateMany
 */
export type PunishmentsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Punishments.
   */
  data: Prisma.XOR<Prisma.PunishmentsUpdateManyMutationInput, Prisma.PunishmentsUncheckedUpdateManyInput>
  /**
   * Filter which Punishments to update
   */
  where?: Prisma.PunishmentsWhereInput
  /**
   * Limit how many Punishments to update.
   */
  limit?: number
}

/**
 * Punishments updateManyAndReturn
 */
export type PunishmentsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Punishments
   */
  select?: Prisma.PunishmentsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Punishments
   */
  omit?: Prisma.PunishmentsOmit<ExtArgs> | null
  /**
   * The data used to update Punishments.
   */
  data: Prisma.XOR<Prisma.PunishmentsUpdateManyMutationInput, Prisma.PunishmentsUncheckedUpdateManyInput>
  /**
   * Filter which Punishments to update
   */
  where?: Prisma.PunishmentsWhereInput
  /**
   * Limit how many Punishments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PunishmentsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Punishments upsert
 */
export type PunishmentsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Punishments
   */
  select?: Prisma.PunishmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Punishments
   */
  omit?: Prisma.PunishmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PunishmentsInclude<ExtArgs> | null
  /**
   * The filter to search for the Punishments to update in case it exists.
   */
  where: Prisma.PunishmentsWhereUniqueInput
  /**
   * In case the Punishments found by the `where` argument doesn't exist, create a new Punishments with this data.
   */
  create: Prisma.XOR<Prisma.PunishmentsCreateInput, Prisma.PunishmentsUncheckedCreateInput>
  /**
   * In case the Punishments was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PunishmentsUpdateInput, Prisma.PunishmentsUncheckedUpdateInput>
}

/**
 * Punishments delete
 */
export type PunishmentsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Punishments
   */
  select?: Prisma.PunishmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Punishments
   */
  omit?: Prisma.PunishmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PunishmentsInclude<ExtArgs> | null
  /**
   * Filter which Punishments to delete.
   */
  where: Prisma.PunishmentsWhereUniqueInput
}

/**
 * Punishments deleteMany
 */
export type PunishmentsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Punishments to delete
   */
  where?: Prisma.PunishmentsWhereInput
  /**
   * Limit how many Punishments to delete.
   */
  limit?: number
}

/**
 * Punishments without action
 */
export type PunishmentsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Punishments
   */
  select?: Prisma.PunishmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Punishments
   */
  omit?: Prisma.PunishmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PunishmentsInclude<ExtArgs> | null
}
