
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Reviews` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Reviews
 * 
 */
export type ReviewsModel = runtime.Types.Result.DefaultSelection<Prisma.$ReviewsPayload>

export type AggregateReviews = {
  _count: ReviewsCountAggregateOutputType | null
  _avg: ReviewsAvgAggregateOutputType | null
  _sum: ReviewsSumAggregateOutputType | null
  _min: ReviewsMinAggregateOutputType | null
  _max: ReviewsMaxAggregateOutputType | null
}

export type ReviewsAvgAggregateOutputType = {
  Score: number | null
}

export type ReviewsSumAggregateOutputType = {
  Score: number | null
}

export type ReviewsMinAggregateOutputType = {
  id: string | null
  review: string | null
  Score: number | null
  UserId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ReviewsMaxAggregateOutputType = {
  id: string | null
  review: string | null
  Score: number | null
  UserId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ReviewsCountAggregateOutputType = {
  id: number
  productCode: number
  review: number
  Score: number
  UserId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ReviewsAvgAggregateInputType = {
  Score?: true
}

export type ReviewsSumAggregateInputType = {
  Score?: true
}

export type ReviewsMinAggregateInputType = {
  id?: true
  review?: true
  Score?: true
  UserId?: true
  createdAt?: true
  updatedAt?: true
}

export type ReviewsMaxAggregateInputType = {
  id?: true
  review?: true
  Score?: true
  UserId?: true
  createdAt?: true
  updatedAt?: true
}

export type ReviewsCountAggregateInputType = {
  id?: true
  productCode?: true
  review?: true
  Score?: true
  UserId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ReviewsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Reviews to aggregate.
   */
  where?: Prisma.ReviewsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Reviews to fetch.
   */
  orderBy?: Prisma.ReviewsOrderByWithRelationInput | Prisma.ReviewsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ReviewsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Reviews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Reviews.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Reviews
  **/
  _count?: true | ReviewsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ReviewsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ReviewsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ReviewsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ReviewsMaxAggregateInputType
}

export type GetReviewsAggregateType<T extends ReviewsAggregateArgs> = {
      [P in keyof T & keyof AggregateReviews]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateReviews[P]>
    : Prisma.GetScalarType<T[P], AggregateReviews[P]>
}




export type ReviewsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReviewsWhereInput
  orderBy?: Prisma.ReviewsOrderByWithAggregationInput | Prisma.ReviewsOrderByWithAggregationInput[]
  by: Prisma.ReviewsScalarFieldEnum[] | Prisma.ReviewsScalarFieldEnum
  having?: Prisma.ReviewsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ReviewsCountAggregateInputType | true
  _avg?: ReviewsAvgAggregateInputType
  _sum?: ReviewsSumAggregateInputType
  _min?: ReviewsMinAggregateInputType
  _max?: ReviewsMaxAggregateInputType
}

export type ReviewsGroupByOutputType = {
  id: string
  productCode: string[]
  review: string
  Score: number
  UserId: string
  createdAt: Date
  updatedAt: Date
  _count: ReviewsCountAggregateOutputType | null
  _avg: ReviewsAvgAggregateOutputType | null
  _sum: ReviewsSumAggregateOutputType | null
  _min: ReviewsMinAggregateOutputType | null
  _max: ReviewsMaxAggregateOutputType | null
}

export type GetReviewsGroupByPayload<T extends ReviewsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ReviewsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ReviewsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ReviewsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ReviewsGroupByOutputType[P]>
      }
    >
  >



export type ReviewsWhereInput = {
  AND?: Prisma.ReviewsWhereInput | Prisma.ReviewsWhereInput[]
  OR?: Prisma.ReviewsWhereInput[]
  NOT?: Prisma.ReviewsWhereInput | Prisma.ReviewsWhereInput[]
  id?: Prisma.StringFilter<"Reviews"> | string
  productCode?: Prisma.StringNullableListFilter<"Reviews">
  review?: Prisma.StringFilter<"Reviews"> | string
  Score?: Prisma.IntFilter<"Reviews"> | number
  UserId?: Prisma.StringFilter<"Reviews"> | string
  createdAt?: Prisma.DateTimeFilter<"Reviews"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Reviews"> | Date | string
  User?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type ReviewsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  productCode?: Prisma.SortOrder
  review?: Prisma.SortOrder
  Score?: Prisma.SortOrder
  UserId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  User?: Prisma.UserOrderByWithRelationInput
}

export type ReviewsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ReviewsWhereInput | Prisma.ReviewsWhereInput[]
  OR?: Prisma.ReviewsWhereInput[]
  NOT?: Prisma.ReviewsWhereInput | Prisma.ReviewsWhereInput[]
  productCode?: Prisma.StringNullableListFilter<"Reviews">
  review?: Prisma.StringFilter<"Reviews"> | string
  Score?: Prisma.IntFilter<"Reviews"> | number
  UserId?: Prisma.StringFilter<"Reviews"> | string
  createdAt?: Prisma.DateTimeFilter<"Reviews"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Reviews"> | Date | string
  User?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type ReviewsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  productCode?: Prisma.SortOrder
  review?: Prisma.SortOrder
  Score?: Prisma.SortOrder
  UserId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ReviewsCountOrderByAggregateInput
  _avg?: Prisma.ReviewsAvgOrderByAggregateInput
  _max?: Prisma.ReviewsMaxOrderByAggregateInput
  _min?: Prisma.ReviewsMinOrderByAggregateInput
  _sum?: Prisma.ReviewsSumOrderByAggregateInput
}

export type ReviewsScalarWhereWithAggregatesInput = {
  AND?: Prisma.ReviewsScalarWhereWithAggregatesInput | Prisma.ReviewsScalarWhereWithAggregatesInput[]
  OR?: Prisma.ReviewsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ReviewsScalarWhereWithAggregatesInput | Prisma.ReviewsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Reviews"> | string
  productCode?: Prisma.StringNullableListFilter<"Reviews">
  review?: Prisma.StringWithAggregatesFilter<"Reviews"> | string
  Score?: Prisma.IntWithAggregatesFilter<"Reviews"> | number
  UserId?: Prisma.StringWithAggregatesFilter<"Reviews"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Reviews"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Reviews"> | Date | string
}

export type ReviewsCreateInput = {
  id?: string
  productCode?: Prisma.ReviewsCreateproductCodeInput | string[]
  review: string
  Score: number
  createdAt?: Date | string
  updatedAt?: Date | string
  User: Prisma.UserCreateNestedOneWithoutReviewsInput
}

export type ReviewsUncheckedCreateInput = {
  id?: string
  productCode?: Prisma.ReviewsCreateproductCodeInput | string[]
  review: string
  Score: number
  UserId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ReviewsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productCode?: Prisma.ReviewsUpdateproductCodeInput | string[]
  review?: Prisma.StringFieldUpdateOperationsInput | string
  Score?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  User?: Prisma.UserUpdateOneRequiredWithoutReviewsNestedInput
}

export type ReviewsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productCode?: Prisma.ReviewsUpdateproductCodeInput | string[]
  review?: Prisma.StringFieldUpdateOperationsInput | string
  Score?: Prisma.IntFieldUpdateOperationsInput | number
  UserId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReviewsCreateManyInput = {
  id?: string
  productCode?: Prisma.ReviewsCreateproductCodeInput | string[]
  review: string
  Score: number
  UserId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ReviewsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productCode?: Prisma.ReviewsUpdateproductCodeInput | string[]
  review?: Prisma.StringFieldUpdateOperationsInput | string
  Score?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReviewsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productCode?: Prisma.ReviewsUpdateproductCodeInput | string[]
  review?: Prisma.StringFieldUpdateOperationsInput | string
  Score?: Prisma.IntFieldUpdateOperationsInput | number
  UserId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReviewsListRelationFilter = {
  every?: Prisma.ReviewsWhereInput
  some?: Prisma.ReviewsWhereInput
  none?: Prisma.ReviewsWhereInput
}

export type ReviewsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ReviewsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productCode?: Prisma.SortOrder
  review?: Prisma.SortOrder
  Score?: Prisma.SortOrder
  UserId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ReviewsAvgOrderByAggregateInput = {
  Score?: Prisma.SortOrder
}

export type ReviewsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  review?: Prisma.SortOrder
  Score?: Prisma.SortOrder
  UserId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ReviewsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  review?: Prisma.SortOrder
  Score?: Prisma.SortOrder
  UserId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ReviewsSumOrderByAggregateInput = {
  Score?: Prisma.SortOrder
}

export type ReviewsCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ReviewsCreateWithoutUserInput, Prisma.ReviewsUncheckedCreateWithoutUserInput> | Prisma.ReviewsCreateWithoutUserInput[] | Prisma.ReviewsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ReviewsCreateOrConnectWithoutUserInput | Prisma.ReviewsCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ReviewsCreateManyUserInputEnvelope
  connect?: Prisma.ReviewsWhereUniqueInput | Prisma.ReviewsWhereUniqueInput[]
}

export type ReviewsUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ReviewsCreateWithoutUserInput, Prisma.ReviewsUncheckedCreateWithoutUserInput> | Prisma.ReviewsCreateWithoutUserInput[] | Prisma.ReviewsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ReviewsCreateOrConnectWithoutUserInput | Prisma.ReviewsCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ReviewsCreateManyUserInputEnvelope
  connect?: Prisma.ReviewsWhereUniqueInput | Prisma.ReviewsWhereUniqueInput[]
}

export type ReviewsUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ReviewsCreateWithoutUserInput, Prisma.ReviewsUncheckedCreateWithoutUserInput> | Prisma.ReviewsCreateWithoutUserInput[] | Prisma.ReviewsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ReviewsCreateOrConnectWithoutUserInput | Prisma.ReviewsCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ReviewsUpsertWithWhereUniqueWithoutUserInput | Prisma.ReviewsUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ReviewsCreateManyUserInputEnvelope
  set?: Prisma.ReviewsWhereUniqueInput | Prisma.ReviewsWhereUniqueInput[]
  disconnect?: Prisma.ReviewsWhereUniqueInput | Prisma.ReviewsWhereUniqueInput[]
  delete?: Prisma.ReviewsWhereUniqueInput | Prisma.ReviewsWhereUniqueInput[]
  connect?: Prisma.ReviewsWhereUniqueInput | Prisma.ReviewsWhereUniqueInput[]
  update?: Prisma.ReviewsUpdateWithWhereUniqueWithoutUserInput | Prisma.ReviewsUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ReviewsUpdateManyWithWhereWithoutUserInput | Prisma.ReviewsUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ReviewsScalarWhereInput | Prisma.ReviewsScalarWhereInput[]
}

export type ReviewsUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ReviewsCreateWithoutUserInput, Prisma.ReviewsUncheckedCreateWithoutUserInput> | Prisma.ReviewsCreateWithoutUserInput[] | Prisma.ReviewsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ReviewsCreateOrConnectWithoutUserInput | Prisma.ReviewsCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ReviewsUpsertWithWhereUniqueWithoutUserInput | Prisma.ReviewsUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ReviewsCreateManyUserInputEnvelope
  set?: Prisma.ReviewsWhereUniqueInput | Prisma.ReviewsWhereUniqueInput[]
  disconnect?: Prisma.ReviewsWhereUniqueInput | Prisma.ReviewsWhereUniqueInput[]
  delete?: Prisma.ReviewsWhereUniqueInput | Prisma.ReviewsWhereUniqueInput[]
  connect?: Prisma.ReviewsWhereUniqueInput | Prisma.ReviewsWhereUniqueInput[]
  update?: Prisma.ReviewsUpdateWithWhereUniqueWithoutUserInput | Prisma.ReviewsUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ReviewsUpdateManyWithWhereWithoutUserInput | Prisma.ReviewsUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ReviewsScalarWhereInput | Prisma.ReviewsScalarWhereInput[]
}

export type ReviewsCreateproductCodeInput = {
  set: string[]
}

export type ReviewsUpdateproductCodeInput = {
  set?: string[]
  push?: string | string[]
}

export type ReviewsCreateWithoutUserInput = {
  id?: string
  productCode?: Prisma.ReviewsCreateproductCodeInput | string[]
  review: string
  Score: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ReviewsUncheckedCreateWithoutUserInput = {
  id?: string
  productCode?: Prisma.ReviewsCreateproductCodeInput | string[]
  review: string
  Score: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ReviewsCreateOrConnectWithoutUserInput = {
  where: Prisma.ReviewsWhereUniqueInput
  create: Prisma.XOR<Prisma.ReviewsCreateWithoutUserInput, Prisma.ReviewsUncheckedCreateWithoutUserInput>
}

export type ReviewsCreateManyUserInputEnvelope = {
  data: Prisma.ReviewsCreateManyUserInput | Prisma.ReviewsCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type ReviewsUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ReviewsWhereUniqueInput
  update: Prisma.XOR<Prisma.ReviewsUpdateWithoutUserInput, Prisma.ReviewsUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ReviewsCreateWithoutUserInput, Prisma.ReviewsUncheckedCreateWithoutUserInput>
}

export type ReviewsUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ReviewsWhereUniqueInput
  data: Prisma.XOR<Prisma.ReviewsUpdateWithoutUserInput, Prisma.ReviewsUncheckedUpdateWithoutUserInput>
}

export type ReviewsUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ReviewsScalarWhereInput
  data: Prisma.XOR<Prisma.ReviewsUpdateManyMutationInput, Prisma.ReviewsUncheckedUpdateManyWithoutUserInput>
}

export type ReviewsScalarWhereInput = {
  AND?: Prisma.ReviewsScalarWhereInput | Prisma.ReviewsScalarWhereInput[]
  OR?: Prisma.ReviewsScalarWhereInput[]
  NOT?: Prisma.ReviewsScalarWhereInput | Prisma.ReviewsScalarWhereInput[]
  id?: Prisma.StringFilter<"Reviews"> | string
  productCode?: Prisma.StringNullableListFilter<"Reviews">
  review?: Prisma.StringFilter<"Reviews"> | string
  Score?: Prisma.IntFilter<"Reviews"> | number
  UserId?: Prisma.StringFilter<"Reviews"> | string
  createdAt?: Prisma.DateTimeFilter<"Reviews"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Reviews"> | Date | string
}

export type ReviewsCreateManyUserInput = {
  id?: string
  productCode?: Prisma.ReviewsCreateproductCodeInput | string[]
  review: string
  Score: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ReviewsUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productCode?: Prisma.ReviewsUpdateproductCodeInput | string[]
  review?: Prisma.StringFieldUpdateOperationsInput | string
  Score?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReviewsUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productCode?: Prisma.ReviewsUpdateproductCodeInput | string[]
  review?: Prisma.StringFieldUpdateOperationsInput | string
  Score?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReviewsUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productCode?: Prisma.ReviewsUpdateproductCodeInput | string[]
  review?: Prisma.StringFieldUpdateOperationsInput | string
  Score?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ReviewsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productCode?: boolean
  review?: boolean
  Score?: boolean
  UserId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["reviews"]>

export type ReviewsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productCode?: boolean
  review?: boolean
  Score?: boolean
  UserId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["reviews"]>

export type ReviewsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productCode?: boolean
  review?: boolean
  Score?: boolean
  UserId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["reviews"]>

export type ReviewsSelectScalar = {
  id?: boolean
  productCode?: boolean
  review?: boolean
  Score?: boolean
  UserId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ReviewsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "productCode" | "review" | "Score" | "UserId" | "createdAt" | "updatedAt", ExtArgs["result"]["reviews"]>
export type ReviewsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type ReviewsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type ReviewsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $ReviewsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Reviews"
  objects: {
    User: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    productCode: string[]
    review: string
    Score: number
    UserId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["reviews"]>
  composites: {}
}

export type ReviewsGetPayload<S extends boolean | null | undefined | ReviewsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ReviewsPayload, S>

export type ReviewsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ReviewsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ReviewsCountAggregateInputType | true
  }

export interface ReviewsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Reviews'], meta: { name: 'Reviews' } }
  /**
   * Find zero or one Reviews that matches the filter.
   * @param {ReviewsFindUniqueArgs} args - Arguments to find a Reviews
   * @example
   * // Get one Reviews
   * const reviews = await prisma.reviews.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ReviewsFindUniqueArgs>(args: Prisma.SelectSubset<T, ReviewsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ReviewsClient<runtime.Types.Result.GetResult<Prisma.$ReviewsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Reviews that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ReviewsFindUniqueOrThrowArgs} args - Arguments to find a Reviews
   * @example
   * // Get one Reviews
   * const reviews = await prisma.reviews.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ReviewsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ReviewsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReviewsClient<runtime.Types.Result.GetResult<Prisma.$ReviewsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Reviews that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReviewsFindFirstArgs} args - Arguments to find a Reviews
   * @example
   * // Get one Reviews
   * const reviews = await prisma.reviews.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ReviewsFindFirstArgs>(args?: Prisma.SelectSubset<T, ReviewsFindFirstArgs<ExtArgs>>): Prisma.Prisma__ReviewsClient<runtime.Types.Result.GetResult<Prisma.$ReviewsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Reviews that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReviewsFindFirstOrThrowArgs} args - Arguments to find a Reviews
   * @example
   * // Get one Reviews
   * const reviews = await prisma.reviews.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ReviewsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ReviewsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReviewsClient<runtime.Types.Result.GetResult<Prisma.$ReviewsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Reviews that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReviewsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Reviews
   * const reviews = await prisma.reviews.findMany()
   * 
   * // Get first 10 Reviews
   * const reviews = await prisma.reviews.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const reviewsWithIdOnly = await prisma.reviews.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ReviewsFindManyArgs>(args?: Prisma.SelectSubset<T, ReviewsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReviewsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Reviews.
   * @param {ReviewsCreateArgs} args - Arguments to create a Reviews.
   * @example
   * // Create one Reviews
   * const Reviews = await prisma.reviews.create({
   *   data: {
   *     // ... data to create a Reviews
   *   }
   * })
   * 
   */
  create<T extends ReviewsCreateArgs>(args: Prisma.SelectSubset<T, ReviewsCreateArgs<ExtArgs>>): Prisma.Prisma__ReviewsClient<runtime.Types.Result.GetResult<Prisma.$ReviewsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Reviews.
   * @param {ReviewsCreateManyArgs} args - Arguments to create many Reviews.
   * @example
   * // Create many Reviews
   * const reviews = await prisma.reviews.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ReviewsCreateManyArgs>(args?: Prisma.SelectSubset<T, ReviewsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Reviews and returns the data saved in the database.
   * @param {ReviewsCreateManyAndReturnArgs} args - Arguments to create many Reviews.
   * @example
   * // Create many Reviews
   * const reviews = await prisma.reviews.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Reviews and only return the `id`
   * const reviewsWithIdOnly = await prisma.reviews.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ReviewsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ReviewsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReviewsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Reviews.
   * @param {ReviewsDeleteArgs} args - Arguments to delete one Reviews.
   * @example
   * // Delete one Reviews
   * const Reviews = await prisma.reviews.delete({
   *   where: {
   *     // ... filter to delete one Reviews
   *   }
   * })
   * 
   */
  delete<T extends ReviewsDeleteArgs>(args: Prisma.SelectSubset<T, ReviewsDeleteArgs<ExtArgs>>): Prisma.Prisma__ReviewsClient<runtime.Types.Result.GetResult<Prisma.$ReviewsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Reviews.
   * @param {ReviewsUpdateArgs} args - Arguments to update one Reviews.
   * @example
   * // Update one Reviews
   * const reviews = await prisma.reviews.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ReviewsUpdateArgs>(args: Prisma.SelectSubset<T, ReviewsUpdateArgs<ExtArgs>>): Prisma.Prisma__ReviewsClient<runtime.Types.Result.GetResult<Prisma.$ReviewsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Reviews.
   * @param {ReviewsDeleteManyArgs} args - Arguments to filter Reviews to delete.
   * @example
   * // Delete a few Reviews
   * const { count } = await prisma.reviews.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ReviewsDeleteManyArgs>(args?: Prisma.SelectSubset<T, ReviewsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Reviews.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReviewsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Reviews
   * const reviews = await prisma.reviews.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ReviewsUpdateManyArgs>(args: Prisma.SelectSubset<T, ReviewsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Reviews and returns the data updated in the database.
   * @param {ReviewsUpdateManyAndReturnArgs} args - Arguments to update many Reviews.
   * @example
   * // Update many Reviews
   * const reviews = await prisma.reviews.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Reviews and only return the `id`
   * const reviewsWithIdOnly = await prisma.reviews.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ReviewsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ReviewsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReviewsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Reviews.
   * @param {ReviewsUpsertArgs} args - Arguments to update or create a Reviews.
   * @example
   * // Update or create a Reviews
   * const reviews = await prisma.reviews.upsert({
   *   create: {
   *     // ... data to create a Reviews
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Reviews we want to update
   *   }
   * })
   */
  upsert<T extends ReviewsUpsertArgs>(args: Prisma.SelectSubset<T, ReviewsUpsertArgs<ExtArgs>>): Prisma.Prisma__ReviewsClient<runtime.Types.Result.GetResult<Prisma.$ReviewsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Reviews.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReviewsCountArgs} args - Arguments to filter Reviews to count.
   * @example
   * // Count the number of Reviews
   * const count = await prisma.reviews.count({
   *   where: {
   *     // ... the filter for the Reviews we want to count
   *   }
   * })
  **/
  count<T extends ReviewsCountArgs>(
    args?: Prisma.Subset<T, ReviewsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ReviewsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Reviews.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReviewsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ReviewsAggregateArgs>(args: Prisma.Subset<T, ReviewsAggregateArgs>): Prisma.PrismaPromise<GetReviewsAggregateType<T>>

  /**
   * Group by Reviews.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReviewsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ReviewsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ReviewsGroupByArgs['orderBy'] }
      : { orderBy?: ReviewsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ReviewsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetReviewsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Reviews model
 */
readonly fields: ReviewsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Reviews.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ReviewsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  User<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Reviews model
 */
export interface ReviewsFieldRefs {
  readonly id: Prisma.FieldRef<"Reviews", 'String'>
  readonly productCode: Prisma.FieldRef<"Reviews", 'String[]'>
  readonly review: Prisma.FieldRef<"Reviews", 'String'>
  readonly Score: Prisma.FieldRef<"Reviews", 'Int'>
  readonly UserId: Prisma.FieldRef<"Reviews", 'String'>
  readonly createdAt: Prisma.FieldRef<"Reviews", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Reviews", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Reviews findUnique
 */
export type ReviewsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reviews
   */
  select?: Prisma.ReviewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reviews
   */
  omit?: Prisma.ReviewsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewsInclude<ExtArgs> | null
  /**
   * Filter, which Reviews to fetch.
   */
  where: Prisma.ReviewsWhereUniqueInput
}

/**
 * Reviews findUniqueOrThrow
 */
export type ReviewsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reviews
   */
  select?: Prisma.ReviewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reviews
   */
  omit?: Prisma.ReviewsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewsInclude<ExtArgs> | null
  /**
   * Filter, which Reviews to fetch.
   */
  where: Prisma.ReviewsWhereUniqueInput
}

/**
 * Reviews findFirst
 */
export type ReviewsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reviews
   */
  select?: Prisma.ReviewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reviews
   */
  omit?: Prisma.ReviewsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewsInclude<ExtArgs> | null
  /**
   * Filter, which Reviews to fetch.
   */
  where?: Prisma.ReviewsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Reviews to fetch.
   */
  orderBy?: Prisma.ReviewsOrderByWithRelationInput | Prisma.ReviewsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Reviews.
   */
  cursor?: Prisma.ReviewsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Reviews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Reviews.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Reviews.
   */
  distinct?: Prisma.ReviewsScalarFieldEnum | Prisma.ReviewsScalarFieldEnum[]
}

/**
 * Reviews findFirstOrThrow
 */
export type ReviewsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reviews
   */
  select?: Prisma.ReviewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reviews
   */
  omit?: Prisma.ReviewsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewsInclude<ExtArgs> | null
  /**
   * Filter, which Reviews to fetch.
   */
  where?: Prisma.ReviewsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Reviews to fetch.
   */
  orderBy?: Prisma.ReviewsOrderByWithRelationInput | Prisma.ReviewsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Reviews.
   */
  cursor?: Prisma.ReviewsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Reviews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Reviews.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Reviews.
   */
  distinct?: Prisma.ReviewsScalarFieldEnum | Prisma.ReviewsScalarFieldEnum[]
}

/**
 * Reviews findMany
 */
export type ReviewsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reviews
   */
  select?: Prisma.ReviewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reviews
   */
  omit?: Prisma.ReviewsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewsInclude<ExtArgs> | null
  /**
   * Filter, which Reviews to fetch.
   */
  where?: Prisma.ReviewsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Reviews to fetch.
   */
  orderBy?: Prisma.ReviewsOrderByWithRelationInput | Prisma.ReviewsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Reviews.
   */
  cursor?: Prisma.ReviewsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Reviews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Reviews.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Reviews.
   */
  distinct?: Prisma.ReviewsScalarFieldEnum | Prisma.ReviewsScalarFieldEnum[]
}

/**
 * Reviews create
 */
export type ReviewsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reviews
   */
  select?: Prisma.ReviewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reviews
   */
  omit?: Prisma.ReviewsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewsInclude<ExtArgs> | null
  /**
   * The data needed to create a Reviews.
   */
  data: Prisma.XOR<Prisma.ReviewsCreateInput, Prisma.ReviewsUncheckedCreateInput>
}

/**
 * Reviews createMany
 */
export type ReviewsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Reviews.
   */
  data: Prisma.ReviewsCreateManyInput | Prisma.ReviewsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Reviews createManyAndReturn
 */
export type ReviewsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reviews
   */
  select?: Prisma.ReviewsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Reviews
   */
  omit?: Prisma.ReviewsOmit<ExtArgs> | null
  /**
   * The data used to create many Reviews.
   */
  data: Prisma.ReviewsCreateManyInput | Prisma.ReviewsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Reviews update
 */
export type ReviewsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reviews
   */
  select?: Prisma.ReviewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reviews
   */
  omit?: Prisma.ReviewsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewsInclude<ExtArgs> | null
  /**
   * The data needed to update a Reviews.
   */
  data: Prisma.XOR<Prisma.ReviewsUpdateInput, Prisma.ReviewsUncheckedUpdateInput>
  /**
   * Choose, which Reviews to update.
   */
  where: Prisma.ReviewsWhereUniqueInput
}

/**
 * Reviews updateMany
 */
export type ReviewsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Reviews.
   */
  data: Prisma.XOR<Prisma.ReviewsUpdateManyMutationInput, Prisma.ReviewsUncheckedUpdateManyInput>
  /**
   * Filter which Reviews to update
   */
  where?: Prisma.ReviewsWhereInput
  /**
   * Limit how many Reviews to update.
   */
  limit?: number
}

/**
 * Reviews updateManyAndReturn
 */
export type ReviewsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reviews
   */
  select?: Prisma.ReviewsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Reviews
   */
  omit?: Prisma.ReviewsOmit<ExtArgs> | null
  /**
   * The data used to update Reviews.
   */
  data: Prisma.XOR<Prisma.ReviewsUpdateManyMutationInput, Prisma.ReviewsUncheckedUpdateManyInput>
  /**
   * Filter which Reviews to update
   */
  where?: Prisma.ReviewsWhereInput
  /**
   * Limit how many Reviews to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Reviews upsert
 */
export type ReviewsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reviews
   */
  select?: Prisma.ReviewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reviews
   */
  omit?: Prisma.ReviewsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewsInclude<ExtArgs> | null
  /**
   * The filter to search for the Reviews to update in case it exists.
   */
  where: Prisma.ReviewsWhereUniqueInput
  /**
   * In case the Reviews found by the `where` argument doesn't exist, create a new Reviews with this data.
   */
  create: Prisma.XOR<Prisma.ReviewsCreateInput, Prisma.ReviewsUncheckedCreateInput>
  /**
   * In case the Reviews was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ReviewsUpdateInput, Prisma.ReviewsUncheckedUpdateInput>
}

/**
 * Reviews delete
 */
export type ReviewsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reviews
   */
  select?: Prisma.ReviewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reviews
   */
  omit?: Prisma.ReviewsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewsInclude<ExtArgs> | null
  /**
   * Filter which Reviews to delete.
   */
  where: Prisma.ReviewsWhereUniqueInput
}

/**
 * Reviews deleteMany
 */
export type ReviewsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Reviews to delete
   */
  where?: Prisma.ReviewsWhereInput
  /**
   * Limit how many Reviews to delete.
   */
  limit?: number
}

/**
 * Reviews without action
 */
export type ReviewsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reviews
   */
  select?: Prisma.ReviewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reviews
   */
  omit?: Prisma.ReviewsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewsInclude<ExtArgs> | null
}
