
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TicketPriorities` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model TicketPriorities
 * 
 */
export type TicketPrioritiesModel = runtime.Types.Result.DefaultSelection<Prisma.$TicketPrioritiesPayload>

export type AggregateTicketPriorities = {
  _count: TicketPrioritiesCountAggregateOutputType | null
  _avg: TicketPrioritiesAvgAggregateOutputType | null
  _sum: TicketPrioritiesSumAggregateOutputType | null
  _min: TicketPrioritiesMinAggregateOutputType | null
  _max: TicketPrioritiesMaxAggregateOutputType | null
}

export type TicketPrioritiesAvgAggregateOutputType = {
  escalationCount: number | null
}

export type TicketPrioritiesSumAggregateOutputType = {
  escalationCount: number | null
}

export type TicketPrioritiesMinAggregateOutputType = {
  id: string | null
  channelId: string | null
  priority: $Enums.TicketPriority | null
  slaDeadline: Date | null
  lastStaffResponse: Date | null
  escalationStarted: Date | null
  escalationCount: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TicketPrioritiesMaxAggregateOutputType = {
  id: string | null
  channelId: string | null
  priority: $Enums.TicketPriority | null
  slaDeadline: Date | null
  lastStaffResponse: Date | null
  escalationStarted: Date | null
  escalationCount: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TicketPrioritiesCountAggregateOutputType = {
  id: number
  channelId: number
  priority: number
  slaDeadline: number
  lastStaffResponse: number
  escalationStarted: number
  escalationCount: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TicketPrioritiesAvgAggregateInputType = {
  escalationCount?: true
}

export type TicketPrioritiesSumAggregateInputType = {
  escalationCount?: true
}

export type TicketPrioritiesMinAggregateInputType = {
  id?: true
  channelId?: true
  priority?: true
  slaDeadline?: true
  lastStaffResponse?: true
  escalationStarted?: true
  escalationCount?: true
  createdAt?: true
  updatedAt?: true
}

export type TicketPrioritiesMaxAggregateInputType = {
  id?: true
  channelId?: true
  priority?: true
  slaDeadline?: true
  lastStaffResponse?: true
  escalationStarted?: true
  escalationCount?: true
  createdAt?: true
  updatedAt?: true
}

export type TicketPrioritiesCountAggregateInputType = {
  id?: true
  channelId?: true
  priority?: true
  slaDeadline?: true
  lastStaffResponse?: true
  escalationStarted?: true
  escalationCount?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TicketPrioritiesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TicketPriorities to aggregate.
   */
  where?: Prisma.TicketPrioritiesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TicketPriorities to fetch.
   */
  orderBy?: Prisma.TicketPrioritiesOrderByWithRelationInput | Prisma.TicketPrioritiesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TicketPrioritiesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TicketPriorities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TicketPriorities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TicketPriorities
  **/
  _count?: true | TicketPrioritiesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TicketPrioritiesAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TicketPrioritiesSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TicketPrioritiesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TicketPrioritiesMaxAggregateInputType
}

export type GetTicketPrioritiesAggregateType<T extends TicketPrioritiesAggregateArgs> = {
      [P in keyof T & keyof AggregateTicketPriorities]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTicketPriorities[P]>
    : Prisma.GetScalarType<T[P], AggregateTicketPriorities[P]>
}




export type TicketPrioritiesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TicketPrioritiesWhereInput
  orderBy?: Prisma.TicketPrioritiesOrderByWithAggregationInput | Prisma.TicketPrioritiesOrderByWithAggregationInput[]
  by: Prisma.TicketPrioritiesScalarFieldEnum[] | Prisma.TicketPrioritiesScalarFieldEnum
  having?: Prisma.TicketPrioritiesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TicketPrioritiesCountAggregateInputType | true
  _avg?: TicketPrioritiesAvgAggregateInputType
  _sum?: TicketPrioritiesSumAggregateInputType
  _min?: TicketPrioritiesMinAggregateInputType
  _max?: TicketPrioritiesMaxAggregateInputType
}

export type TicketPrioritiesGroupByOutputType = {
  id: string
  channelId: string
  priority: $Enums.TicketPriority
  slaDeadline: Date
  lastStaffResponse: Date | null
  escalationStarted: Date | null
  escalationCount: number
  createdAt: Date
  updatedAt: Date
  _count: TicketPrioritiesCountAggregateOutputType | null
  _avg: TicketPrioritiesAvgAggregateOutputType | null
  _sum: TicketPrioritiesSumAggregateOutputType | null
  _min: TicketPrioritiesMinAggregateOutputType | null
  _max: TicketPrioritiesMaxAggregateOutputType | null
}

export type GetTicketPrioritiesGroupByPayload<T extends TicketPrioritiesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TicketPrioritiesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TicketPrioritiesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TicketPrioritiesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TicketPrioritiesGroupByOutputType[P]>
      }
    >
  >



export type TicketPrioritiesWhereInput = {
  AND?: Prisma.TicketPrioritiesWhereInput | Prisma.TicketPrioritiesWhereInput[]
  OR?: Prisma.TicketPrioritiesWhereInput[]
  NOT?: Prisma.TicketPrioritiesWhereInput | Prisma.TicketPrioritiesWhereInput[]
  id?: Prisma.StringFilter<"TicketPriorities"> | string
  channelId?: Prisma.StringFilter<"TicketPriorities"> | string
  priority?: Prisma.EnumTicketPriorityFilter<"TicketPriorities"> | $Enums.TicketPriority
  slaDeadline?: Prisma.DateTimeFilter<"TicketPriorities"> | Date | string
  lastStaffResponse?: Prisma.DateTimeNullableFilter<"TicketPriorities"> | Date | string | null
  escalationStarted?: Prisma.DateTimeNullableFilter<"TicketPriorities"> | Date | string | null
  escalationCount?: Prisma.IntFilter<"TicketPriorities"> | number
  createdAt?: Prisma.DateTimeFilter<"TicketPriorities"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TicketPriorities"> | Date | string
}

export type TicketPrioritiesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  slaDeadline?: Prisma.SortOrder
  lastStaffResponse?: Prisma.SortOrderInput | Prisma.SortOrder
  escalationStarted?: Prisma.SortOrderInput | Prisma.SortOrder
  escalationCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TicketPrioritiesWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  channelId?: string
  AND?: Prisma.TicketPrioritiesWhereInput | Prisma.TicketPrioritiesWhereInput[]
  OR?: Prisma.TicketPrioritiesWhereInput[]
  NOT?: Prisma.TicketPrioritiesWhereInput | Prisma.TicketPrioritiesWhereInput[]
  priority?: Prisma.EnumTicketPriorityFilter<"TicketPriorities"> | $Enums.TicketPriority
  slaDeadline?: Prisma.DateTimeFilter<"TicketPriorities"> | Date | string
  lastStaffResponse?: Prisma.DateTimeNullableFilter<"TicketPriorities"> | Date | string | null
  escalationStarted?: Prisma.DateTimeNullableFilter<"TicketPriorities"> | Date | string | null
  escalationCount?: Prisma.IntFilter<"TicketPriorities"> | number
  createdAt?: Prisma.DateTimeFilter<"TicketPriorities"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TicketPriorities"> | Date | string
}, "id" | "channelId">

export type TicketPrioritiesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  slaDeadline?: Prisma.SortOrder
  lastStaffResponse?: Prisma.SortOrderInput | Prisma.SortOrder
  escalationStarted?: Prisma.SortOrderInput | Prisma.SortOrder
  escalationCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TicketPrioritiesCountOrderByAggregateInput
  _avg?: Prisma.TicketPrioritiesAvgOrderByAggregateInput
  _max?: Prisma.TicketPrioritiesMaxOrderByAggregateInput
  _min?: Prisma.TicketPrioritiesMinOrderByAggregateInput
  _sum?: Prisma.TicketPrioritiesSumOrderByAggregateInput
}

export type TicketPrioritiesScalarWhereWithAggregatesInput = {
  AND?: Prisma.TicketPrioritiesScalarWhereWithAggregatesInput | Prisma.TicketPrioritiesScalarWhereWithAggregatesInput[]
  OR?: Prisma.TicketPrioritiesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TicketPrioritiesScalarWhereWithAggregatesInput | Prisma.TicketPrioritiesScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TicketPriorities"> | string
  channelId?: Prisma.StringWithAggregatesFilter<"TicketPriorities"> | string
  priority?: Prisma.EnumTicketPriorityWithAggregatesFilter<"TicketPriorities"> | $Enums.TicketPriority
  slaDeadline?: Prisma.DateTimeWithAggregatesFilter<"TicketPriorities"> | Date | string
  lastStaffResponse?: Prisma.DateTimeNullableWithAggregatesFilter<"TicketPriorities"> | Date | string | null
  escalationStarted?: Prisma.DateTimeNullableWithAggregatesFilter<"TicketPriorities"> | Date | string | null
  escalationCount?: Prisma.IntWithAggregatesFilter<"TicketPriorities"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TicketPriorities"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TicketPriorities"> | Date | string
}

export type TicketPrioritiesCreateInput = {
  id?: string
  channelId: string
  priority?: $Enums.TicketPriority
  slaDeadline: Date | string
  lastStaffResponse?: Date | string | null
  escalationStarted?: Date | string | null
  escalationCount?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TicketPrioritiesUncheckedCreateInput = {
  id?: string
  channelId: string
  priority?: $Enums.TicketPriority
  slaDeadline: Date | string
  lastStaffResponse?: Date | string | null
  escalationStarted?: Date | string | null
  escalationCount?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TicketPrioritiesUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.EnumTicketPriorityFieldUpdateOperationsInput | $Enums.TicketPriority
  slaDeadline?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastStaffResponse?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  escalationStarted?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  escalationCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TicketPrioritiesUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.EnumTicketPriorityFieldUpdateOperationsInput | $Enums.TicketPriority
  slaDeadline?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastStaffResponse?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  escalationStarted?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  escalationCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TicketPrioritiesCreateManyInput = {
  id?: string
  channelId: string
  priority?: $Enums.TicketPriority
  slaDeadline: Date | string
  lastStaffResponse?: Date | string | null
  escalationStarted?: Date | string | null
  escalationCount?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TicketPrioritiesUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.EnumTicketPriorityFieldUpdateOperationsInput | $Enums.TicketPriority
  slaDeadline?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastStaffResponse?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  escalationStarted?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  escalationCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TicketPrioritiesUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.EnumTicketPriorityFieldUpdateOperationsInput | $Enums.TicketPriority
  slaDeadline?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastStaffResponse?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  escalationStarted?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  escalationCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TicketPrioritiesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  slaDeadline?: Prisma.SortOrder
  lastStaffResponse?: Prisma.SortOrder
  escalationStarted?: Prisma.SortOrder
  escalationCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TicketPrioritiesAvgOrderByAggregateInput = {
  escalationCount?: Prisma.SortOrder
}

export type TicketPrioritiesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  slaDeadline?: Prisma.SortOrder
  lastStaffResponse?: Prisma.SortOrder
  escalationStarted?: Prisma.SortOrder
  escalationCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TicketPrioritiesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  slaDeadline?: Prisma.SortOrder
  lastStaffResponse?: Prisma.SortOrder
  escalationStarted?: Prisma.SortOrder
  escalationCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TicketPrioritiesSumOrderByAggregateInput = {
  escalationCount?: Prisma.SortOrder
}

export type EnumTicketPriorityFieldUpdateOperationsInput = {
  set?: $Enums.TicketPriority
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}



export type TicketPrioritiesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  channelId?: boolean
  priority?: boolean
  slaDeadline?: boolean
  lastStaffResponse?: boolean
  escalationStarted?: boolean
  escalationCount?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["ticketPriorities"]>

export type TicketPrioritiesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  channelId?: boolean
  priority?: boolean
  slaDeadline?: boolean
  lastStaffResponse?: boolean
  escalationStarted?: boolean
  escalationCount?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["ticketPriorities"]>

export type TicketPrioritiesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  channelId?: boolean
  priority?: boolean
  slaDeadline?: boolean
  lastStaffResponse?: boolean
  escalationStarted?: boolean
  escalationCount?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["ticketPriorities"]>

export type TicketPrioritiesSelectScalar = {
  id?: boolean
  channelId?: boolean
  priority?: boolean
  slaDeadline?: boolean
  lastStaffResponse?: boolean
  escalationStarted?: boolean
  escalationCount?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TicketPrioritiesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "channelId" | "priority" | "slaDeadline" | "lastStaffResponse" | "escalationStarted" | "escalationCount" | "createdAt" | "updatedAt", ExtArgs["result"]["ticketPriorities"]>

export type $TicketPrioritiesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TicketPriorities"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    channelId: string
    priority: $Enums.TicketPriority
    slaDeadline: Date
    lastStaffResponse: Date | null
    escalationStarted: Date | null
    escalationCount: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["ticketPriorities"]>
  composites: {}
}

export type TicketPrioritiesGetPayload<S extends boolean | null | undefined | TicketPrioritiesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TicketPrioritiesPayload, S>

export type TicketPrioritiesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TicketPrioritiesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TicketPrioritiesCountAggregateInputType | true
  }

export interface TicketPrioritiesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TicketPriorities'], meta: { name: 'TicketPriorities' } }
  /**
   * Find zero or one TicketPriorities that matches the filter.
   * @param {TicketPrioritiesFindUniqueArgs} args - Arguments to find a TicketPriorities
   * @example
   * // Get one TicketPriorities
   * const ticketPriorities = await prisma.ticketPriorities.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TicketPrioritiesFindUniqueArgs>(args: Prisma.SelectSubset<T, TicketPrioritiesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TicketPrioritiesClient<runtime.Types.Result.GetResult<Prisma.$TicketPrioritiesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TicketPriorities that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TicketPrioritiesFindUniqueOrThrowArgs} args - Arguments to find a TicketPriorities
   * @example
   * // Get one TicketPriorities
   * const ticketPriorities = await prisma.ticketPriorities.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TicketPrioritiesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TicketPrioritiesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TicketPrioritiesClient<runtime.Types.Result.GetResult<Prisma.$TicketPrioritiesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TicketPriorities that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketPrioritiesFindFirstArgs} args - Arguments to find a TicketPriorities
   * @example
   * // Get one TicketPriorities
   * const ticketPriorities = await prisma.ticketPriorities.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TicketPrioritiesFindFirstArgs>(args?: Prisma.SelectSubset<T, TicketPrioritiesFindFirstArgs<ExtArgs>>): Prisma.Prisma__TicketPrioritiesClient<runtime.Types.Result.GetResult<Prisma.$TicketPrioritiesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TicketPriorities that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketPrioritiesFindFirstOrThrowArgs} args - Arguments to find a TicketPriorities
   * @example
   * // Get one TicketPriorities
   * const ticketPriorities = await prisma.ticketPriorities.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TicketPrioritiesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TicketPrioritiesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TicketPrioritiesClient<runtime.Types.Result.GetResult<Prisma.$TicketPrioritiesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TicketPriorities that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketPrioritiesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TicketPriorities
   * const ticketPriorities = await prisma.ticketPriorities.findMany()
   * 
   * // Get first 10 TicketPriorities
   * const ticketPriorities = await prisma.ticketPriorities.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const ticketPrioritiesWithIdOnly = await prisma.ticketPriorities.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TicketPrioritiesFindManyArgs>(args?: Prisma.SelectSubset<T, TicketPrioritiesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TicketPrioritiesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TicketPriorities.
   * @param {TicketPrioritiesCreateArgs} args - Arguments to create a TicketPriorities.
   * @example
   * // Create one TicketPriorities
   * const TicketPriorities = await prisma.ticketPriorities.create({
   *   data: {
   *     // ... data to create a TicketPriorities
   *   }
   * })
   * 
   */
  create<T extends TicketPrioritiesCreateArgs>(args: Prisma.SelectSubset<T, TicketPrioritiesCreateArgs<ExtArgs>>): Prisma.Prisma__TicketPrioritiesClient<runtime.Types.Result.GetResult<Prisma.$TicketPrioritiesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TicketPriorities.
   * @param {TicketPrioritiesCreateManyArgs} args - Arguments to create many TicketPriorities.
   * @example
   * // Create many TicketPriorities
   * const ticketPriorities = await prisma.ticketPriorities.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TicketPrioritiesCreateManyArgs>(args?: Prisma.SelectSubset<T, TicketPrioritiesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TicketPriorities and returns the data saved in the database.
   * @param {TicketPrioritiesCreateManyAndReturnArgs} args - Arguments to create many TicketPriorities.
   * @example
   * // Create many TicketPriorities
   * const ticketPriorities = await prisma.ticketPriorities.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TicketPriorities and only return the `id`
   * const ticketPrioritiesWithIdOnly = await prisma.ticketPriorities.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TicketPrioritiesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TicketPrioritiesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TicketPrioritiesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TicketPriorities.
   * @param {TicketPrioritiesDeleteArgs} args - Arguments to delete one TicketPriorities.
   * @example
   * // Delete one TicketPriorities
   * const TicketPriorities = await prisma.ticketPriorities.delete({
   *   where: {
   *     // ... filter to delete one TicketPriorities
   *   }
   * })
   * 
   */
  delete<T extends TicketPrioritiesDeleteArgs>(args: Prisma.SelectSubset<T, TicketPrioritiesDeleteArgs<ExtArgs>>): Prisma.Prisma__TicketPrioritiesClient<runtime.Types.Result.GetResult<Prisma.$TicketPrioritiesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TicketPriorities.
   * @param {TicketPrioritiesUpdateArgs} args - Arguments to update one TicketPriorities.
   * @example
   * // Update one TicketPriorities
   * const ticketPriorities = await prisma.ticketPriorities.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TicketPrioritiesUpdateArgs>(args: Prisma.SelectSubset<T, TicketPrioritiesUpdateArgs<ExtArgs>>): Prisma.Prisma__TicketPrioritiesClient<runtime.Types.Result.GetResult<Prisma.$TicketPrioritiesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TicketPriorities.
   * @param {TicketPrioritiesDeleteManyArgs} args - Arguments to filter TicketPriorities to delete.
   * @example
   * // Delete a few TicketPriorities
   * const { count } = await prisma.ticketPriorities.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TicketPrioritiesDeleteManyArgs>(args?: Prisma.SelectSubset<T, TicketPrioritiesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TicketPriorities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketPrioritiesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TicketPriorities
   * const ticketPriorities = await prisma.ticketPriorities.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TicketPrioritiesUpdateManyArgs>(args: Prisma.SelectSubset<T, TicketPrioritiesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TicketPriorities and returns the data updated in the database.
   * @param {TicketPrioritiesUpdateManyAndReturnArgs} args - Arguments to update many TicketPriorities.
   * @example
   * // Update many TicketPriorities
   * const ticketPriorities = await prisma.ticketPriorities.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TicketPriorities and only return the `id`
   * const ticketPrioritiesWithIdOnly = await prisma.ticketPriorities.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TicketPrioritiesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TicketPrioritiesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TicketPrioritiesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TicketPriorities.
   * @param {TicketPrioritiesUpsertArgs} args - Arguments to update or create a TicketPriorities.
   * @example
   * // Update or create a TicketPriorities
   * const ticketPriorities = await prisma.ticketPriorities.upsert({
   *   create: {
   *     // ... data to create a TicketPriorities
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TicketPriorities we want to update
   *   }
   * })
   */
  upsert<T extends TicketPrioritiesUpsertArgs>(args: Prisma.SelectSubset<T, TicketPrioritiesUpsertArgs<ExtArgs>>): Prisma.Prisma__TicketPrioritiesClient<runtime.Types.Result.GetResult<Prisma.$TicketPrioritiesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TicketPriorities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketPrioritiesCountArgs} args - Arguments to filter TicketPriorities to count.
   * @example
   * // Count the number of TicketPriorities
   * const count = await prisma.ticketPriorities.count({
   *   where: {
   *     // ... the filter for the TicketPriorities we want to count
   *   }
   * })
  **/
  count<T extends TicketPrioritiesCountArgs>(
    args?: Prisma.Subset<T, TicketPrioritiesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TicketPrioritiesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TicketPriorities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketPrioritiesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TicketPrioritiesAggregateArgs>(args: Prisma.Subset<T, TicketPrioritiesAggregateArgs>): Prisma.PrismaPromise<GetTicketPrioritiesAggregateType<T>>

  /**
   * Group by TicketPriorities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketPrioritiesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TicketPrioritiesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TicketPrioritiesGroupByArgs['orderBy'] }
      : { orderBy?: TicketPrioritiesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TicketPrioritiesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTicketPrioritiesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TicketPriorities model
 */
readonly fields: TicketPrioritiesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TicketPriorities.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TicketPrioritiesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TicketPriorities model
 */
export interface TicketPrioritiesFieldRefs {
  readonly id: Prisma.FieldRef<"TicketPriorities", 'String'>
  readonly channelId: Prisma.FieldRef<"TicketPriorities", 'String'>
  readonly priority: Prisma.FieldRef<"TicketPriorities", 'TicketPriority'>
  readonly slaDeadline: Prisma.FieldRef<"TicketPriorities", 'DateTime'>
  readonly lastStaffResponse: Prisma.FieldRef<"TicketPriorities", 'DateTime'>
  readonly escalationStarted: Prisma.FieldRef<"TicketPriorities", 'DateTime'>
  readonly escalationCount: Prisma.FieldRef<"TicketPriorities", 'Int'>
  readonly createdAt: Prisma.FieldRef<"TicketPriorities", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TicketPriorities", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TicketPriorities findUnique
 */
export type TicketPrioritiesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketPriorities
   */
  select?: Prisma.TicketPrioritiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketPriorities
   */
  omit?: Prisma.TicketPrioritiesOmit<ExtArgs> | null
  /**
   * Filter, which TicketPriorities to fetch.
   */
  where: Prisma.TicketPrioritiesWhereUniqueInput
}

/**
 * TicketPriorities findUniqueOrThrow
 */
export type TicketPrioritiesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketPriorities
   */
  select?: Prisma.TicketPrioritiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketPriorities
   */
  omit?: Prisma.TicketPrioritiesOmit<ExtArgs> | null
  /**
   * Filter, which TicketPriorities to fetch.
   */
  where: Prisma.TicketPrioritiesWhereUniqueInput
}

/**
 * TicketPriorities findFirst
 */
export type TicketPrioritiesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketPriorities
   */
  select?: Prisma.TicketPrioritiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketPriorities
   */
  omit?: Prisma.TicketPrioritiesOmit<ExtArgs> | null
  /**
   * Filter, which TicketPriorities to fetch.
   */
  where?: Prisma.TicketPrioritiesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TicketPriorities to fetch.
   */
  orderBy?: Prisma.TicketPrioritiesOrderByWithRelationInput | Prisma.TicketPrioritiesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TicketPriorities.
   */
  cursor?: Prisma.TicketPrioritiesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TicketPriorities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TicketPriorities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TicketPriorities.
   */
  distinct?: Prisma.TicketPrioritiesScalarFieldEnum | Prisma.TicketPrioritiesScalarFieldEnum[]
}

/**
 * TicketPriorities findFirstOrThrow
 */
export type TicketPrioritiesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketPriorities
   */
  select?: Prisma.TicketPrioritiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketPriorities
   */
  omit?: Prisma.TicketPrioritiesOmit<ExtArgs> | null
  /**
   * Filter, which TicketPriorities to fetch.
   */
  where?: Prisma.TicketPrioritiesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TicketPriorities to fetch.
   */
  orderBy?: Prisma.TicketPrioritiesOrderByWithRelationInput | Prisma.TicketPrioritiesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TicketPriorities.
   */
  cursor?: Prisma.TicketPrioritiesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TicketPriorities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TicketPriorities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TicketPriorities.
   */
  distinct?: Prisma.TicketPrioritiesScalarFieldEnum | Prisma.TicketPrioritiesScalarFieldEnum[]
}

/**
 * TicketPriorities findMany
 */
export type TicketPrioritiesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketPriorities
   */
  select?: Prisma.TicketPrioritiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketPriorities
   */
  omit?: Prisma.TicketPrioritiesOmit<ExtArgs> | null
  /**
   * Filter, which TicketPriorities to fetch.
   */
  where?: Prisma.TicketPrioritiesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TicketPriorities to fetch.
   */
  orderBy?: Prisma.TicketPrioritiesOrderByWithRelationInput | Prisma.TicketPrioritiesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TicketPriorities.
   */
  cursor?: Prisma.TicketPrioritiesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TicketPriorities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TicketPriorities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TicketPriorities.
   */
  distinct?: Prisma.TicketPrioritiesScalarFieldEnum | Prisma.TicketPrioritiesScalarFieldEnum[]
}

/**
 * TicketPriorities create
 */
export type TicketPrioritiesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketPriorities
   */
  select?: Prisma.TicketPrioritiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketPriorities
   */
  omit?: Prisma.TicketPrioritiesOmit<ExtArgs> | null
  /**
   * The data needed to create a TicketPriorities.
   */
  data: Prisma.XOR<Prisma.TicketPrioritiesCreateInput, Prisma.TicketPrioritiesUncheckedCreateInput>
}

/**
 * TicketPriorities createMany
 */
export type TicketPrioritiesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TicketPriorities.
   */
  data: Prisma.TicketPrioritiesCreateManyInput | Prisma.TicketPrioritiesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TicketPriorities createManyAndReturn
 */
export type TicketPrioritiesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketPriorities
   */
  select?: Prisma.TicketPrioritiesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TicketPriorities
   */
  omit?: Prisma.TicketPrioritiesOmit<ExtArgs> | null
  /**
   * The data used to create many TicketPriorities.
   */
  data: Prisma.TicketPrioritiesCreateManyInput | Prisma.TicketPrioritiesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TicketPriorities update
 */
export type TicketPrioritiesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketPriorities
   */
  select?: Prisma.TicketPrioritiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketPriorities
   */
  omit?: Prisma.TicketPrioritiesOmit<ExtArgs> | null
  /**
   * The data needed to update a TicketPriorities.
   */
  data: Prisma.XOR<Prisma.TicketPrioritiesUpdateInput, Prisma.TicketPrioritiesUncheckedUpdateInput>
  /**
   * Choose, which TicketPriorities to update.
   */
  where: Prisma.TicketPrioritiesWhereUniqueInput
}

/**
 * TicketPriorities updateMany
 */
export type TicketPrioritiesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TicketPriorities.
   */
  data: Prisma.XOR<Prisma.TicketPrioritiesUpdateManyMutationInput, Prisma.TicketPrioritiesUncheckedUpdateManyInput>
  /**
   * Filter which TicketPriorities to update
   */
  where?: Prisma.TicketPrioritiesWhereInput
  /**
   * Limit how many TicketPriorities to update.
   */
  limit?: number
}

/**
 * TicketPriorities updateManyAndReturn
 */
export type TicketPrioritiesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketPriorities
   */
  select?: Prisma.TicketPrioritiesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TicketPriorities
   */
  omit?: Prisma.TicketPrioritiesOmit<ExtArgs> | null
  /**
   * The data used to update TicketPriorities.
   */
  data: Prisma.XOR<Prisma.TicketPrioritiesUpdateManyMutationInput, Prisma.TicketPrioritiesUncheckedUpdateManyInput>
  /**
   * Filter which TicketPriorities to update
   */
  where?: Prisma.TicketPrioritiesWhereInput
  /**
   * Limit how many TicketPriorities to update.
   */
  limit?: number
}

/**
 * TicketPriorities upsert
 */
export type TicketPrioritiesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketPriorities
   */
  select?: Prisma.TicketPrioritiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketPriorities
   */
  omit?: Prisma.TicketPrioritiesOmit<ExtArgs> | null
  /**
   * The filter to search for the TicketPriorities to update in case it exists.
   */
  where: Prisma.TicketPrioritiesWhereUniqueInput
  /**
   * In case the TicketPriorities found by the `where` argument doesn't exist, create a new TicketPriorities with this data.
   */
  create: Prisma.XOR<Prisma.TicketPrioritiesCreateInput, Prisma.TicketPrioritiesUncheckedCreateInput>
  /**
   * In case the TicketPriorities was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TicketPrioritiesUpdateInput, Prisma.TicketPrioritiesUncheckedUpdateInput>
}

/**
 * TicketPriorities delete
 */
export type TicketPrioritiesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketPriorities
   */
  select?: Prisma.TicketPrioritiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketPriorities
   */
  omit?: Prisma.TicketPrioritiesOmit<ExtArgs> | null
  /**
   * Filter which TicketPriorities to delete.
   */
  where: Prisma.TicketPrioritiesWhereUniqueInput
}

/**
 * TicketPriorities deleteMany
 */
export type TicketPrioritiesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TicketPriorities to delete
   */
  where?: Prisma.TicketPrioritiesWhereInput
  /**
   * Limit how many TicketPriorities to delete.
   */
  limit?: number
}

/**
 * TicketPriorities without action
 */
export type TicketPrioritiesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketPriorities
   */
  select?: Prisma.TicketPrioritiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketPriorities
   */
  omit?: Prisma.TicketPrioritiesOmit<ExtArgs> | null
}
