
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Transfers` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Transfers
 * 
 */
export type TransfersModel = runtime.Types.Result.DefaultSelection<Prisma.$TransfersPayload>

export type AggregateTransfers = {
  _count: TransfersCountAggregateOutputType | null
  _min: TransfersMinAggregateOutputType | null
  _max: TransfersMaxAggregateOutputType | null
}

export type TransfersMinAggregateOutputType = {
  id: string | null
  transferReason: string | null
  TransactionId: string | null
  NewUserId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TransfersMaxAggregateOutputType = {
  id: string | null
  transferReason: string | null
  TransactionId: string | null
  NewUserId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TransfersCountAggregateOutputType = {
  id: number
  transferReason: number
  TransactionId: number
  NewUserId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TransfersMinAggregateInputType = {
  id?: true
  transferReason?: true
  TransactionId?: true
  NewUserId?: true
  createdAt?: true
  updatedAt?: true
}

export type TransfersMaxAggregateInputType = {
  id?: true
  transferReason?: true
  TransactionId?: true
  NewUserId?: true
  createdAt?: true
  updatedAt?: true
}

export type TransfersCountAggregateInputType = {
  id?: true
  transferReason?: true
  TransactionId?: true
  NewUserId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TransfersAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Transfers to aggregate.
   */
  where?: Prisma.TransfersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Transfers to fetch.
   */
  orderBy?: Prisma.TransfersOrderByWithRelationInput | Prisma.TransfersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TransfersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Transfers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Transfers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Transfers
  **/
  _count?: true | TransfersCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TransfersMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TransfersMaxAggregateInputType
}

export type GetTransfersAggregateType<T extends TransfersAggregateArgs> = {
      [P in keyof T & keyof AggregateTransfers]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTransfers[P]>
    : Prisma.GetScalarType<T[P], AggregateTransfers[P]>
}




export type TransfersGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TransfersWhereInput
  orderBy?: Prisma.TransfersOrderByWithAggregationInput | Prisma.TransfersOrderByWithAggregationInput[]
  by: Prisma.TransfersScalarFieldEnum[] | Prisma.TransfersScalarFieldEnum
  having?: Prisma.TransfersScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TransfersCountAggregateInputType | true
  _min?: TransfersMinAggregateInputType
  _max?: TransfersMaxAggregateInputType
}

export type TransfersGroupByOutputType = {
  id: string
  transferReason: string
  TransactionId: string
  NewUserId: string
  createdAt: Date
  updatedAt: Date
  _count: TransfersCountAggregateOutputType | null
  _min: TransfersMinAggregateOutputType | null
  _max: TransfersMaxAggregateOutputType | null
}

export type GetTransfersGroupByPayload<T extends TransfersGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TransfersGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TransfersGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TransfersGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TransfersGroupByOutputType[P]>
      }
    >
  >



export type TransfersWhereInput = {
  AND?: Prisma.TransfersWhereInput | Prisma.TransfersWhereInput[]
  OR?: Prisma.TransfersWhereInput[]
  NOT?: Prisma.TransfersWhereInput | Prisma.TransfersWhereInput[]
  id?: Prisma.StringFilter<"Transfers"> | string
  transferReason?: Prisma.StringFilter<"Transfers"> | string
  TransactionId?: Prisma.StringFilter<"Transfers"> | string
  NewUserId?: Prisma.StringFilter<"Transfers"> | string
  createdAt?: Prisma.DateTimeFilter<"Transfers"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Transfers"> | Date | string
  Transaction?: Prisma.XOR<Prisma.TransactionsScalarRelationFilter, Prisma.TransactionsWhereInput>
  NewUser?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type TransfersOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  transferReason?: Prisma.SortOrder
  TransactionId?: Prisma.SortOrder
  NewUserId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  Transaction?: Prisma.TransactionsOrderByWithRelationInput
  NewUser?: Prisma.UserOrderByWithRelationInput
}

export type TransfersWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TransfersWhereInput | Prisma.TransfersWhereInput[]
  OR?: Prisma.TransfersWhereInput[]
  NOT?: Prisma.TransfersWhereInput | Prisma.TransfersWhereInput[]
  transferReason?: Prisma.StringFilter<"Transfers"> | string
  TransactionId?: Prisma.StringFilter<"Transfers"> | string
  NewUserId?: Prisma.StringFilter<"Transfers"> | string
  createdAt?: Prisma.DateTimeFilter<"Transfers"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Transfers"> | Date | string
  Transaction?: Prisma.XOR<Prisma.TransactionsScalarRelationFilter, Prisma.TransactionsWhereInput>
  NewUser?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type TransfersOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  transferReason?: Prisma.SortOrder
  TransactionId?: Prisma.SortOrder
  NewUserId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TransfersCountOrderByAggregateInput
  _max?: Prisma.TransfersMaxOrderByAggregateInput
  _min?: Prisma.TransfersMinOrderByAggregateInput
}

export type TransfersScalarWhereWithAggregatesInput = {
  AND?: Prisma.TransfersScalarWhereWithAggregatesInput | Prisma.TransfersScalarWhereWithAggregatesInput[]
  OR?: Prisma.TransfersScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TransfersScalarWhereWithAggregatesInput | Prisma.TransfersScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Transfers"> | string
  transferReason?: Prisma.StringWithAggregatesFilter<"Transfers"> | string
  TransactionId?: Prisma.StringWithAggregatesFilter<"Transfers"> | string
  NewUserId?: Prisma.StringWithAggregatesFilter<"Transfers"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Transfers"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Transfers"> | Date | string
}

export type TransfersCreateInput = {
  id?: string
  transferReason: string
  createdAt?: Date | string
  updatedAt?: Date | string
  Transaction: Prisma.TransactionsCreateNestedOneWithoutTransfersInput
  NewUser: Prisma.UserCreateNestedOneWithoutTransfersInput
}

export type TransfersUncheckedCreateInput = {
  id?: string
  transferReason: string
  TransactionId: string
  NewUserId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TransfersUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transferReason?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Transaction?: Prisma.TransactionsUpdateOneRequiredWithoutTransfersNestedInput
  NewUser?: Prisma.UserUpdateOneRequiredWithoutTransfersNestedInput
}

export type TransfersUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transferReason?: Prisma.StringFieldUpdateOperationsInput | string
  TransactionId?: Prisma.StringFieldUpdateOperationsInput | string
  NewUserId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TransfersCreateManyInput = {
  id?: string
  transferReason: string
  TransactionId: string
  NewUserId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TransfersUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transferReason?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TransfersUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transferReason?: Prisma.StringFieldUpdateOperationsInput | string
  TransactionId?: Prisma.StringFieldUpdateOperationsInput | string
  NewUserId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TransfersListRelationFilter = {
  every?: Prisma.TransfersWhereInput
  some?: Prisma.TransfersWhereInput
  none?: Prisma.TransfersWhereInput
}

export type TransfersOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TransfersCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  transferReason?: Prisma.SortOrder
  TransactionId?: Prisma.SortOrder
  NewUserId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TransfersMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  transferReason?: Prisma.SortOrder
  TransactionId?: Prisma.SortOrder
  NewUserId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TransfersMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  transferReason?: Prisma.SortOrder
  TransactionId?: Prisma.SortOrder
  NewUserId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TransfersCreateNestedManyWithoutNewUserInput = {
  create?: Prisma.XOR<Prisma.TransfersCreateWithoutNewUserInput, Prisma.TransfersUncheckedCreateWithoutNewUserInput> | Prisma.TransfersCreateWithoutNewUserInput[] | Prisma.TransfersUncheckedCreateWithoutNewUserInput[]
  connectOrCreate?: Prisma.TransfersCreateOrConnectWithoutNewUserInput | Prisma.TransfersCreateOrConnectWithoutNewUserInput[]
  createMany?: Prisma.TransfersCreateManyNewUserInputEnvelope
  connect?: Prisma.TransfersWhereUniqueInput | Prisma.TransfersWhereUniqueInput[]
}

export type TransfersUncheckedCreateNestedManyWithoutNewUserInput = {
  create?: Prisma.XOR<Prisma.TransfersCreateWithoutNewUserInput, Prisma.TransfersUncheckedCreateWithoutNewUserInput> | Prisma.TransfersCreateWithoutNewUserInput[] | Prisma.TransfersUncheckedCreateWithoutNewUserInput[]
  connectOrCreate?: Prisma.TransfersCreateOrConnectWithoutNewUserInput | Prisma.TransfersCreateOrConnectWithoutNewUserInput[]
  createMany?: Prisma.TransfersCreateManyNewUserInputEnvelope
  connect?: Prisma.TransfersWhereUniqueInput | Prisma.TransfersWhereUniqueInput[]
}

export type TransfersUpdateManyWithoutNewUserNestedInput = {
  create?: Prisma.XOR<Prisma.TransfersCreateWithoutNewUserInput, Prisma.TransfersUncheckedCreateWithoutNewUserInput> | Prisma.TransfersCreateWithoutNewUserInput[] | Prisma.TransfersUncheckedCreateWithoutNewUserInput[]
  connectOrCreate?: Prisma.TransfersCreateOrConnectWithoutNewUserInput | Prisma.TransfersCreateOrConnectWithoutNewUserInput[]
  upsert?: Prisma.TransfersUpsertWithWhereUniqueWithoutNewUserInput | Prisma.TransfersUpsertWithWhereUniqueWithoutNewUserInput[]
  createMany?: Prisma.TransfersCreateManyNewUserInputEnvelope
  set?: Prisma.TransfersWhereUniqueInput | Prisma.TransfersWhereUniqueInput[]
  disconnect?: Prisma.TransfersWhereUniqueInput | Prisma.TransfersWhereUniqueInput[]
  delete?: Prisma.TransfersWhereUniqueInput | Prisma.TransfersWhereUniqueInput[]
  connect?: Prisma.TransfersWhereUniqueInput | Prisma.TransfersWhereUniqueInput[]
  update?: Prisma.TransfersUpdateWithWhereUniqueWithoutNewUserInput | Prisma.TransfersUpdateWithWhereUniqueWithoutNewUserInput[]
  updateMany?: Prisma.TransfersUpdateManyWithWhereWithoutNewUserInput | Prisma.TransfersUpdateManyWithWhereWithoutNewUserInput[]
  deleteMany?: Prisma.TransfersScalarWhereInput | Prisma.TransfersScalarWhereInput[]
}

export type TransfersUncheckedUpdateManyWithoutNewUserNestedInput = {
  create?: Prisma.XOR<Prisma.TransfersCreateWithoutNewUserInput, Prisma.TransfersUncheckedCreateWithoutNewUserInput> | Prisma.TransfersCreateWithoutNewUserInput[] | Prisma.TransfersUncheckedCreateWithoutNewUserInput[]
  connectOrCreate?: Prisma.TransfersCreateOrConnectWithoutNewUserInput | Prisma.TransfersCreateOrConnectWithoutNewUserInput[]
  upsert?: Prisma.TransfersUpsertWithWhereUniqueWithoutNewUserInput | Prisma.TransfersUpsertWithWhereUniqueWithoutNewUserInput[]
  createMany?: Prisma.TransfersCreateManyNewUserInputEnvelope
  set?: Prisma.TransfersWhereUniqueInput | Prisma.TransfersWhereUniqueInput[]
  disconnect?: Prisma.TransfersWhereUniqueInput | Prisma.TransfersWhereUniqueInput[]
  delete?: Prisma.TransfersWhereUniqueInput | Prisma.TransfersWhereUniqueInput[]
  connect?: Prisma.TransfersWhereUniqueInput | Prisma.TransfersWhereUniqueInput[]
  update?: Prisma.TransfersUpdateWithWhereUniqueWithoutNewUserInput | Prisma.TransfersUpdateWithWhereUniqueWithoutNewUserInput[]
  updateMany?: Prisma.TransfersUpdateManyWithWhereWithoutNewUserInput | Prisma.TransfersUpdateManyWithWhereWithoutNewUserInput[]
  deleteMany?: Prisma.TransfersScalarWhereInput | Prisma.TransfersScalarWhereInput[]
}

export type TransfersCreateNestedManyWithoutTransactionInput = {
  create?: Prisma.XOR<Prisma.TransfersCreateWithoutTransactionInput, Prisma.TransfersUncheckedCreateWithoutTransactionInput> | Prisma.TransfersCreateWithoutTransactionInput[] | Prisma.TransfersUncheckedCreateWithoutTransactionInput[]
  connectOrCreate?: Prisma.TransfersCreateOrConnectWithoutTransactionInput | Prisma.TransfersCreateOrConnectWithoutTransactionInput[]
  createMany?: Prisma.TransfersCreateManyTransactionInputEnvelope
  connect?: Prisma.TransfersWhereUniqueInput | Prisma.TransfersWhereUniqueInput[]
}

export type TransfersUncheckedCreateNestedManyWithoutTransactionInput = {
  create?: Prisma.XOR<Prisma.TransfersCreateWithoutTransactionInput, Prisma.TransfersUncheckedCreateWithoutTransactionInput> | Prisma.TransfersCreateWithoutTransactionInput[] | Prisma.TransfersUncheckedCreateWithoutTransactionInput[]
  connectOrCreate?: Prisma.TransfersCreateOrConnectWithoutTransactionInput | Prisma.TransfersCreateOrConnectWithoutTransactionInput[]
  createMany?: Prisma.TransfersCreateManyTransactionInputEnvelope
  connect?: Prisma.TransfersWhereUniqueInput | Prisma.TransfersWhereUniqueInput[]
}

export type TransfersUpdateManyWithoutTransactionNestedInput = {
  create?: Prisma.XOR<Prisma.TransfersCreateWithoutTransactionInput, Prisma.TransfersUncheckedCreateWithoutTransactionInput> | Prisma.TransfersCreateWithoutTransactionInput[] | Prisma.TransfersUncheckedCreateWithoutTransactionInput[]
  connectOrCreate?: Prisma.TransfersCreateOrConnectWithoutTransactionInput | Prisma.TransfersCreateOrConnectWithoutTransactionInput[]
  upsert?: Prisma.TransfersUpsertWithWhereUniqueWithoutTransactionInput | Prisma.TransfersUpsertWithWhereUniqueWithoutTransactionInput[]
  createMany?: Prisma.TransfersCreateManyTransactionInputEnvelope
  set?: Prisma.TransfersWhereUniqueInput | Prisma.TransfersWhereUniqueInput[]
  disconnect?: Prisma.TransfersWhereUniqueInput | Prisma.TransfersWhereUniqueInput[]
  delete?: Prisma.TransfersWhereUniqueInput | Prisma.TransfersWhereUniqueInput[]
  connect?: Prisma.TransfersWhereUniqueInput | Prisma.TransfersWhereUniqueInput[]
  update?: Prisma.TransfersUpdateWithWhereUniqueWithoutTransactionInput | Prisma.TransfersUpdateWithWhereUniqueWithoutTransactionInput[]
  updateMany?: Prisma.TransfersUpdateManyWithWhereWithoutTransactionInput | Prisma.TransfersUpdateManyWithWhereWithoutTransactionInput[]
  deleteMany?: Prisma.TransfersScalarWhereInput | Prisma.TransfersScalarWhereInput[]
}

export type TransfersUncheckedUpdateManyWithoutTransactionNestedInput = {
  create?: Prisma.XOR<Prisma.TransfersCreateWithoutTransactionInput, Prisma.TransfersUncheckedCreateWithoutTransactionInput> | Prisma.TransfersCreateWithoutTransactionInput[] | Prisma.TransfersUncheckedCreateWithoutTransactionInput[]
  connectOrCreate?: Prisma.TransfersCreateOrConnectWithoutTransactionInput | Prisma.TransfersCreateOrConnectWithoutTransactionInput[]
  upsert?: Prisma.TransfersUpsertWithWhereUniqueWithoutTransactionInput | Prisma.TransfersUpsertWithWhereUniqueWithoutTransactionInput[]
  createMany?: Prisma.TransfersCreateManyTransactionInputEnvelope
  set?: Prisma.TransfersWhereUniqueInput | Prisma.TransfersWhereUniqueInput[]
  disconnect?: Prisma.TransfersWhereUniqueInput | Prisma.TransfersWhereUniqueInput[]
  delete?: Prisma.TransfersWhereUniqueInput | Prisma.TransfersWhereUniqueInput[]
  connect?: Prisma.TransfersWhereUniqueInput | Prisma.TransfersWhereUniqueInput[]
  update?: Prisma.TransfersUpdateWithWhereUniqueWithoutTransactionInput | Prisma.TransfersUpdateWithWhereUniqueWithoutTransactionInput[]
  updateMany?: Prisma.TransfersUpdateManyWithWhereWithoutTransactionInput | Prisma.TransfersUpdateManyWithWhereWithoutTransactionInput[]
  deleteMany?: Prisma.TransfersScalarWhereInput | Prisma.TransfersScalarWhereInput[]
}

export type TransfersCreateWithoutNewUserInput = {
  id?: string
  transferReason: string
  createdAt?: Date | string
  updatedAt?: Date | string
  Transaction: Prisma.TransactionsCreateNestedOneWithoutTransfersInput
}

export type TransfersUncheckedCreateWithoutNewUserInput = {
  id?: string
  transferReason: string
  TransactionId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TransfersCreateOrConnectWithoutNewUserInput = {
  where: Prisma.TransfersWhereUniqueInput
  create: Prisma.XOR<Prisma.TransfersCreateWithoutNewUserInput, Prisma.TransfersUncheckedCreateWithoutNewUserInput>
}

export type TransfersCreateManyNewUserInputEnvelope = {
  data: Prisma.TransfersCreateManyNewUserInput | Prisma.TransfersCreateManyNewUserInput[]
  skipDuplicates?: boolean
}

export type TransfersUpsertWithWhereUniqueWithoutNewUserInput = {
  where: Prisma.TransfersWhereUniqueInput
  update: Prisma.XOR<Prisma.TransfersUpdateWithoutNewUserInput, Prisma.TransfersUncheckedUpdateWithoutNewUserInput>
  create: Prisma.XOR<Prisma.TransfersCreateWithoutNewUserInput, Prisma.TransfersUncheckedCreateWithoutNewUserInput>
}

export type TransfersUpdateWithWhereUniqueWithoutNewUserInput = {
  where: Prisma.TransfersWhereUniqueInput
  data: Prisma.XOR<Prisma.TransfersUpdateWithoutNewUserInput, Prisma.TransfersUncheckedUpdateWithoutNewUserInput>
}

export type TransfersUpdateManyWithWhereWithoutNewUserInput = {
  where: Prisma.TransfersScalarWhereInput
  data: Prisma.XOR<Prisma.TransfersUpdateManyMutationInput, Prisma.TransfersUncheckedUpdateManyWithoutNewUserInput>
}

export type TransfersScalarWhereInput = {
  AND?: Prisma.TransfersScalarWhereInput | Prisma.TransfersScalarWhereInput[]
  OR?: Prisma.TransfersScalarWhereInput[]
  NOT?: Prisma.TransfersScalarWhereInput | Prisma.TransfersScalarWhereInput[]
  id?: Prisma.StringFilter<"Transfers"> | string
  transferReason?: Prisma.StringFilter<"Transfers"> | string
  TransactionId?: Prisma.StringFilter<"Transfers"> | string
  NewUserId?: Prisma.StringFilter<"Transfers"> | string
  createdAt?: Prisma.DateTimeFilter<"Transfers"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Transfers"> | Date | string
}

export type TransfersCreateWithoutTransactionInput = {
  id?: string
  transferReason: string
  createdAt?: Date | string
  updatedAt?: Date | string
  NewUser: Prisma.UserCreateNestedOneWithoutTransfersInput
}

export type TransfersUncheckedCreateWithoutTransactionInput = {
  id?: string
  transferReason: string
  NewUserId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TransfersCreateOrConnectWithoutTransactionInput = {
  where: Prisma.TransfersWhereUniqueInput
  create: Prisma.XOR<Prisma.TransfersCreateWithoutTransactionInput, Prisma.TransfersUncheckedCreateWithoutTransactionInput>
}

export type TransfersCreateManyTransactionInputEnvelope = {
  data: Prisma.TransfersCreateManyTransactionInput | Prisma.TransfersCreateManyTransactionInput[]
  skipDuplicates?: boolean
}

export type TransfersUpsertWithWhereUniqueWithoutTransactionInput = {
  where: Prisma.TransfersWhereUniqueInput
  update: Prisma.XOR<Prisma.TransfersUpdateWithoutTransactionInput, Prisma.TransfersUncheckedUpdateWithoutTransactionInput>
  create: Prisma.XOR<Prisma.TransfersCreateWithoutTransactionInput, Prisma.TransfersUncheckedCreateWithoutTransactionInput>
}

export type TransfersUpdateWithWhereUniqueWithoutTransactionInput = {
  where: Prisma.TransfersWhereUniqueInput
  data: Prisma.XOR<Prisma.TransfersUpdateWithoutTransactionInput, Prisma.TransfersUncheckedUpdateWithoutTransactionInput>
}

export type TransfersUpdateManyWithWhereWithoutTransactionInput = {
  where: Prisma.TransfersScalarWhereInput
  data: Prisma.XOR<Prisma.TransfersUpdateManyMutationInput, Prisma.TransfersUncheckedUpdateManyWithoutTransactionInput>
}

export type TransfersCreateManyNewUserInput = {
  id?: string
  transferReason: string
  TransactionId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TransfersUpdateWithoutNewUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transferReason?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Transaction?: Prisma.TransactionsUpdateOneRequiredWithoutTransfersNestedInput
}

export type TransfersUncheckedUpdateWithoutNewUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transferReason?: Prisma.StringFieldUpdateOperationsInput | string
  TransactionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TransfersUncheckedUpdateManyWithoutNewUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transferReason?: Prisma.StringFieldUpdateOperationsInput | string
  TransactionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TransfersCreateManyTransactionInput = {
  id?: string
  transferReason: string
  NewUserId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TransfersUpdateWithoutTransactionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transferReason?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  NewUser?: Prisma.UserUpdateOneRequiredWithoutTransfersNestedInput
}

export type TransfersUncheckedUpdateWithoutTransactionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transferReason?: Prisma.StringFieldUpdateOperationsInput | string
  NewUserId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TransfersUncheckedUpdateManyWithoutTransactionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transferReason?: Prisma.StringFieldUpdateOperationsInput | string
  NewUserId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TransfersSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  transferReason?: boolean
  TransactionId?: boolean
  NewUserId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  Transaction?: boolean | Prisma.TransactionsDefaultArgs<ExtArgs>
  NewUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["transfers"]>

export type TransfersSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  transferReason?: boolean
  TransactionId?: boolean
  NewUserId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  Transaction?: boolean | Prisma.TransactionsDefaultArgs<ExtArgs>
  NewUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["transfers"]>

export type TransfersSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  transferReason?: boolean
  TransactionId?: boolean
  NewUserId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  Transaction?: boolean | Prisma.TransactionsDefaultArgs<ExtArgs>
  NewUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["transfers"]>

export type TransfersSelectScalar = {
  id?: boolean
  transferReason?: boolean
  TransactionId?: boolean
  NewUserId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TransfersOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "transferReason" | "TransactionId" | "NewUserId" | "createdAt" | "updatedAt", ExtArgs["result"]["transfers"]>
export type TransfersInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Transaction?: boolean | Prisma.TransactionsDefaultArgs<ExtArgs>
  NewUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type TransfersIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Transaction?: boolean | Prisma.TransactionsDefaultArgs<ExtArgs>
  NewUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type TransfersIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Transaction?: boolean | Prisma.TransactionsDefaultArgs<ExtArgs>
  NewUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $TransfersPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Transfers"
  objects: {
    Transaction: Prisma.$TransactionsPayload<ExtArgs>
    NewUser: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    transferReason: string
    TransactionId: string
    NewUserId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["transfers"]>
  composites: {}
}

export type TransfersGetPayload<S extends boolean | null | undefined | TransfersDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TransfersPayload, S>

export type TransfersCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TransfersFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TransfersCountAggregateInputType | true
  }

export interface TransfersDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Transfers'], meta: { name: 'Transfers' } }
  /**
   * Find zero or one Transfers that matches the filter.
   * @param {TransfersFindUniqueArgs} args - Arguments to find a Transfers
   * @example
   * // Get one Transfers
   * const transfers = await prisma.transfers.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TransfersFindUniqueArgs>(args: Prisma.SelectSubset<T, TransfersFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TransfersClient<runtime.Types.Result.GetResult<Prisma.$TransfersPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Transfers that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TransfersFindUniqueOrThrowArgs} args - Arguments to find a Transfers
   * @example
   * // Get one Transfers
   * const transfers = await prisma.transfers.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TransfersFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TransfersFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TransfersClient<runtime.Types.Result.GetResult<Prisma.$TransfersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Transfers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransfersFindFirstArgs} args - Arguments to find a Transfers
   * @example
   * // Get one Transfers
   * const transfers = await prisma.transfers.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TransfersFindFirstArgs>(args?: Prisma.SelectSubset<T, TransfersFindFirstArgs<ExtArgs>>): Prisma.Prisma__TransfersClient<runtime.Types.Result.GetResult<Prisma.$TransfersPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Transfers that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransfersFindFirstOrThrowArgs} args - Arguments to find a Transfers
   * @example
   * // Get one Transfers
   * const transfers = await prisma.transfers.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TransfersFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TransfersFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TransfersClient<runtime.Types.Result.GetResult<Prisma.$TransfersPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Transfers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransfersFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Transfers
   * const transfers = await prisma.transfers.findMany()
   * 
   * // Get first 10 Transfers
   * const transfers = await prisma.transfers.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const transfersWithIdOnly = await prisma.transfers.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TransfersFindManyArgs>(args?: Prisma.SelectSubset<T, TransfersFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransfersPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Transfers.
   * @param {TransfersCreateArgs} args - Arguments to create a Transfers.
   * @example
   * // Create one Transfers
   * const Transfers = await prisma.transfers.create({
   *   data: {
   *     // ... data to create a Transfers
   *   }
   * })
   * 
   */
  create<T extends TransfersCreateArgs>(args: Prisma.SelectSubset<T, TransfersCreateArgs<ExtArgs>>): Prisma.Prisma__TransfersClient<runtime.Types.Result.GetResult<Prisma.$TransfersPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Transfers.
   * @param {TransfersCreateManyArgs} args - Arguments to create many Transfers.
   * @example
   * // Create many Transfers
   * const transfers = await prisma.transfers.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TransfersCreateManyArgs>(args?: Prisma.SelectSubset<T, TransfersCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Transfers and returns the data saved in the database.
   * @param {TransfersCreateManyAndReturnArgs} args - Arguments to create many Transfers.
   * @example
   * // Create many Transfers
   * const transfers = await prisma.transfers.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Transfers and only return the `id`
   * const transfersWithIdOnly = await prisma.transfers.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TransfersCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TransfersCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransfersPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Transfers.
   * @param {TransfersDeleteArgs} args - Arguments to delete one Transfers.
   * @example
   * // Delete one Transfers
   * const Transfers = await prisma.transfers.delete({
   *   where: {
   *     // ... filter to delete one Transfers
   *   }
   * })
   * 
   */
  delete<T extends TransfersDeleteArgs>(args: Prisma.SelectSubset<T, TransfersDeleteArgs<ExtArgs>>): Prisma.Prisma__TransfersClient<runtime.Types.Result.GetResult<Prisma.$TransfersPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Transfers.
   * @param {TransfersUpdateArgs} args - Arguments to update one Transfers.
   * @example
   * // Update one Transfers
   * const transfers = await prisma.transfers.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TransfersUpdateArgs>(args: Prisma.SelectSubset<T, TransfersUpdateArgs<ExtArgs>>): Prisma.Prisma__TransfersClient<runtime.Types.Result.GetResult<Prisma.$TransfersPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Transfers.
   * @param {TransfersDeleteManyArgs} args - Arguments to filter Transfers to delete.
   * @example
   * // Delete a few Transfers
   * const { count } = await prisma.transfers.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TransfersDeleteManyArgs>(args?: Prisma.SelectSubset<T, TransfersDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Transfers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransfersUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Transfers
   * const transfers = await prisma.transfers.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TransfersUpdateManyArgs>(args: Prisma.SelectSubset<T, TransfersUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Transfers and returns the data updated in the database.
   * @param {TransfersUpdateManyAndReturnArgs} args - Arguments to update many Transfers.
   * @example
   * // Update many Transfers
   * const transfers = await prisma.transfers.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Transfers and only return the `id`
   * const transfersWithIdOnly = await prisma.transfers.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TransfersUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TransfersUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransfersPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Transfers.
   * @param {TransfersUpsertArgs} args - Arguments to update or create a Transfers.
   * @example
   * // Update or create a Transfers
   * const transfers = await prisma.transfers.upsert({
   *   create: {
   *     // ... data to create a Transfers
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Transfers we want to update
   *   }
   * })
   */
  upsert<T extends TransfersUpsertArgs>(args: Prisma.SelectSubset<T, TransfersUpsertArgs<ExtArgs>>): Prisma.Prisma__TransfersClient<runtime.Types.Result.GetResult<Prisma.$TransfersPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Transfers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransfersCountArgs} args - Arguments to filter Transfers to count.
   * @example
   * // Count the number of Transfers
   * const count = await prisma.transfers.count({
   *   where: {
   *     // ... the filter for the Transfers we want to count
   *   }
   * })
  **/
  count<T extends TransfersCountArgs>(
    args?: Prisma.Subset<T, TransfersCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TransfersCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Transfers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransfersAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TransfersAggregateArgs>(args: Prisma.Subset<T, TransfersAggregateArgs>): Prisma.PrismaPromise<GetTransfersAggregateType<T>>

  /**
   * Group by Transfers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransfersGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TransfersGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TransfersGroupByArgs['orderBy'] }
      : { orderBy?: TransfersGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TransfersGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTransfersGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Transfers model
 */
readonly fields: TransfersFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Transfers.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TransfersClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Transaction<T extends Prisma.TransactionsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TransactionsDefaultArgs<ExtArgs>>): Prisma.Prisma__TransactionsClient<runtime.Types.Result.GetResult<Prisma.$TransactionsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  NewUser<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Transfers model
 */
export interface TransfersFieldRefs {
  readonly id: Prisma.FieldRef<"Transfers", 'String'>
  readonly transferReason: Prisma.FieldRef<"Transfers", 'String'>
  readonly TransactionId: Prisma.FieldRef<"Transfers", 'String'>
  readonly NewUserId: Prisma.FieldRef<"Transfers", 'String'>
  readonly createdAt: Prisma.FieldRef<"Transfers", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Transfers", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Transfers findUnique
 */
export type TransfersFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transfers
   */
  select?: Prisma.TransfersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transfers
   */
  omit?: Prisma.TransfersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransfersInclude<ExtArgs> | null
  /**
   * Filter, which Transfers to fetch.
   */
  where: Prisma.TransfersWhereUniqueInput
}

/**
 * Transfers findUniqueOrThrow
 */
export type TransfersFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transfers
   */
  select?: Prisma.TransfersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transfers
   */
  omit?: Prisma.TransfersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransfersInclude<ExtArgs> | null
  /**
   * Filter, which Transfers to fetch.
   */
  where: Prisma.TransfersWhereUniqueInput
}

/**
 * Transfers findFirst
 */
export type TransfersFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transfers
   */
  select?: Prisma.TransfersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transfers
   */
  omit?: Prisma.TransfersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransfersInclude<ExtArgs> | null
  /**
   * Filter, which Transfers to fetch.
   */
  where?: Prisma.TransfersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Transfers to fetch.
   */
  orderBy?: Prisma.TransfersOrderByWithRelationInput | Prisma.TransfersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Transfers.
   */
  cursor?: Prisma.TransfersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Transfers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Transfers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Transfers.
   */
  distinct?: Prisma.TransfersScalarFieldEnum | Prisma.TransfersScalarFieldEnum[]
}

/**
 * Transfers findFirstOrThrow
 */
export type TransfersFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transfers
   */
  select?: Prisma.TransfersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transfers
   */
  omit?: Prisma.TransfersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransfersInclude<ExtArgs> | null
  /**
   * Filter, which Transfers to fetch.
   */
  where?: Prisma.TransfersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Transfers to fetch.
   */
  orderBy?: Prisma.TransfersOrderByWithRelationInput | Prisma.TransfersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Transfers.
   */
  cursor?: Prisma.TransfersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Transfers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Transfers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Transfers.
   */
  distinct?: Prisma.TransfersScalarFieldEnum | Prisma.TransfersScalarFieldEnum[]
}

/**
 * Transfers findMany
 */
export type TransfersFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transfers
   */
  select?: Prisma.TransfersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transfers
   */
  omit?: Prisma.TransfersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransfersInclude<ExtArgs> | null
  /**
   * Filter, which Transfers to fetch.
   */
  where?: Prisma.TransfersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Transfers to fetch.
   */
  orderBy?: Prisma.TransfersOrderByWithRelationInput | Prisma.TransfersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Transfers.
   */
  cursor?: Prisma.TransfersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Transfers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Transfers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Transfers.
   */
  distinct?: Prisma.TransfersScalarFieldEnum | Prisma.TransfersScalarFieldEnum[]
}

/**
 * Transfers create
 */
export type TransfersCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transfers
   */
  select?: Prisma.TransfersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transfers
   */
  omit?: Prisma.TransfersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransfersInclude<ExtArgs> | null
  /**
   * The data needed to create a Transfers.
   */
  data: Prisma.XOR<Prisma.TransfersCreateInput, Prisma.TransfersUncheckedCreateInput>
}

/**
 * Transfers createMany
 */
export type TransfersCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Transfers.
   */
  data: Prisma.TransfersCreateManyInput | Prisma.TransfersCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Transfers createManyAndReturn
 */
export type TransfersCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transfers
   */
  select?: Prisma.TransfersSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Transfers
   */
  omit?: Prisma.TransfersOmit<ExtArgs> | null
  /**
   * The data used to create many Transfers.
   */
  data: Prisma.TransfersCreateManyInput | Prisma.TransfersCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransfersIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Transfers update
 */
export type TransfersUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transfers
   */
  select?: Prisma.TransfersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transfers
   */
  omit?: Prisma.TransfersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransfersInclude<ExtArgs> | null
  /**
   * The data needed to update a Transfers.
   */
  data: Prisma.XOR<Prisma.TransfersUpdateInput, Prisma.TransfersUncheckedUpdateInput>
  /**
   * Choose, which Transfers to update.
   */
  where: Prisma.TransfersWhereUniqueInput
}

/**
 * Transfers updateMany
 */
export type TransfersUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Transfers.
   */
  data: Prisma.XOR<Prisma.TransfersUpdateManyMutationInput, Prisma.TransfersUncheckedUpdateManyInput>
  /**
   * Filter which Transfers to update
   */
  where?: Prisma.TransfersWhereInput
  /**
   * Limit how many Transfers to update.
   */
  limit?: number
}

/**
 * Transfers updateManyAndReturn
 */
export type TransfersUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transfers
   */
  select?: Prisma.TransfersSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Transfers
   */
  omit?: Prisma.TransfersOmit<ExtArgs> | null
  /**
   * The data used to update Transfers.
   */
  data: Prisma.XOR<Prisma.TransfersUpdateManyMutationInput, Prisma.TransfersUncheckedUpdateManyInput>
  /**
   * Filter which Transfers to update
   */
  where?: Prisma.TransfersWhereInput
  /**
   * Limit how many Transfers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransfersIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Transfers upsert
 */
export type TransfersUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transfers
   */
  select?: Prisma.TransfersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transfers
   */
  omit?: Prisma.TransfersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransfersInclude<ExtArgs> | null
  /**
   * The filter to search for the Transfers to update in case it exists.
   */
  where: Prisma.TransfersWhereUniqueInput
  /**
   * In case the Transfers found by the `where` argument doesn't exist, create a new Transfers with this data.
   */
  create: Prisma.XOR<Prisma.TransfersCreateInput, Prisma.TransfersUncheckedCreateInput>
  /**
   * In case the Transfers was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TransfersUpdateInput, Prisma.TransfersUncheckedUpdateInput>
}

/**
 * Transfers delete
 */
export type TransfersDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transfers
   */
  select?: Prisma.TransfersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transfers
   */
  omit?: Prisma.TransfersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransfersInclude<ExtArgs> | null
  /**
   * Filter which Transfers to delete.
   */
  where: Prisma.TransfersWhereUniqueInput
}

/**
 * Transfers deleteMany
 */
export type TransfersDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Transfers to delete
   */
  where?: Prisma.TransfersWhereInput
  /**
   * Limit how many Transfers to delete.
   */
  limit?: number
}

/**
 * Transfers without action
 */
export type TransfersDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transfers
   */
  select?: Prisma.TransfersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transfers
   */
  omit?: Prisma.TransfersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransfersInclude<ExtArgs> | null
}
