import { QSTopic } from '@/types/index.js';

export const topics: QSTopic[] = [
  {
    'id': 'identity_tokens',
    'title': 'What are Identity Tokens?',
    'searchable_queries': [
      'identity tokens',
      'how can I get a new identify token',
      'how do get an identity token?'
    ],
    'support_contents': 'We don\'t use identity tokens anymore, please just ignore identity tokens anytime that you see it.'
  },
  {
    'id': 'roblox_studio_output',
    'title': 'How do I enable Roblox Output (in-studio)?',
    'searchable_queries': [
      'studio output',
      'my products don\'t work'
    ],
    'support_contents': 'Click on the **View** tab and then click on **Output**.'
  },
  {
    'id': 'roblox_game_output',
    'title': 'How do I enable Roblox Output (in-game)?',
    'searchable_queries': [
      'game output',
      'game console',
      'dev console'
    ],
    'support_contents': 'While in-game, press F9 or type `/console` in the game\'s chat.\nAfter that, make sure to click on the "Server" tab of the console.'
  },
  {
    'id': 'templates_output',
    'title': 'Who is "Templates", and why is it logging in my output?',
    'searchable_queries': [
      'templates',
      'what is templates',
      'game_owner_id matched templates_user_id'
    ],
    'support_contents': '"Templates" is the default user generated by Roblox for unpublished games...\nIf you see the user "Templates" in your console, you need to publish your game (press ALT + P), then restart your studio session.'
  },
  {
    'id': 'product_prices',
    'title': 'What are the prices?',
    'searchable_queries': [
      'product prices',
      'what are the prices?',
      'how much do the products cost?'
    ],
    'support_contents': 'Go to the [products page](https://inertia.lighting/products) on our website for prices.\n'
  },
  {
    'id': 'product_purchases',
    'title': 'How do I purchase a product?',
    'searchable_queries': [
      'purchasing products',
      'buying products',
      'where can I buy products?',
      'how do I make a purchase?',
      'How do I buy?',
      'product hub'
    ],
    'support_contents': 'Check out <#601891200273743932> for more info on buying our products.'
  },
  {
    'id': 'product_usage',
    'title': 'How do I use the products that I bought?',
    'searchable_queries': [
      'using products'
    ],
    'support_contents': 'Check out <#601891200273743932> for more info on using our products.'
  },
  {
    'id': 'refunds',
    'title': 'Can I receive a refund?',
    'searchable_queries': [
      'refunds',
      'can I get a refund for the product',
      'can I get a refund',
      'I want a refund for the product',
      'I want a refund'
    ],
    'support_contents': 'Currently, we do not offer refunds.\nThe cost of refunding is higher than the amount that we make from each transaction.'
  },
  {
    'id': 'support_tickets',
    'title': 'How do I open a Support Ticket?',
    'searchable_queries': [
      'support',
      'support tickets',
      'opening a support ticket',
      'where can I get support?',
      'i need support',
      'i need help',
      'how do I open ticket',
      'my products don\'t work',
      'Where do I open a ticket?',
      'someone help me',
      'I want to transfer my products',
      'whitelist error',
      'my products don\'t work',
      'hey I need some support',
      'my lights don\'t work',
      'my panels are showing nothing',
      'help',
      'someone help its not working'
    ],
    'support_contents': 'Check out <#814197612491833354> for more information on opening support tickets.'
  },
  {
    'id': 'sharing_products',
    'title': 'Can I share products that I own?',
    'searchable_queries': [
      'sharing products',
      'can I share my products'
    ],
    'support_contents': 'No, unless you are the owner of a Roblox Group\'s games that others can develop in.'
  },
  {
    'id': 'working_for_us',
    'title': 'Can I work for Inertia Lighting?',
    'searchable_queries': [
      'i want to work for inertia?',
      'can I be a developer',
      'how do I apply for staff?',
      'make me an admin!',
      'make me a moderator!',
      'staff applications',
      'are you guys hiring?',
      'are you hiring?',
      'can I work for Inertia?',
      'Hi, how do you become staff?',
      'how become staff?'
    ],
    'support_contents': 'Staff applications are available [here](https://inertia.lighting/staff/applications).'
  },
  {
    'id': 'product_transfers',
    'title': 'Am I able to transfer my product(s)?',
    'searchable_queries': [
      'product transfers'
    ],
    'support_contents': 'Yes, once you transfer your product(s), you will not be able to use those product(s) until you re-purchase them.\nOpen a Product Transfers support ticket to start a transfer!'
  },
  {
    'id': 'enable_http_requests',
    'title': 'How do I enable HTTP Requests in my game?',
    'searchable_queries': [
      'http requests',
      'enable http requests',
      'enabling http requests'
    ],
    'support_contents': 'Open the "Game Settings" menu in Roblox Studio, click on the "Security" tab, enable "HTTP requests", then save changes.'
  },
  {
    'id': 'too_many_http_requests',
    'title': 'How do I fix "number of requests exceeded limit"?',
    'searchable_queries': [
      'too many http requests',
      'number of requests exceeded limit'
    ],
    'support_contents': 'Roblox\'s current limitation for HTTP requests is 20 requests per minute.\nTo work around this, you need to find the script(s) that are making too many requests, then remove those script(s).'
  },
  {
    'id': 'product_downloads',
    'title': 'How do I download products that I have purchased?',
    'searchable_queries': [
      'downloading products',
      'I wasn\'t sent the download',
      'How do I download my products?',
      'What should I do to get the product?',
      'How do I get the model now?',
      'I did not get a file or anything so that I could use them',
      'I did not get a file',
      'I did not receive my product',
      'So I just bought something from the product hub and I don\'t have it',
      'where do i go if i purchased a product',
      'I brought a product from inertia how do I find them in my inv',
      'The product didn\'t show up in my inventory',
      'Where are my products?',
      'How do I get my products?',
      'How can I download an updated product?',
      'i bought the product but where do I download?',
      'How come I do not have my product roles now?',
      'after I buy a product, how do I receive it?',
      'How do I get the download link?',
      'How do I receive the products',
      'where are the files for the lights?'
    ],
    'support_contents': 'Go to the [products page](https://inertia.lighting/products) on our website.\nMake sure to login with the correct discord account!'
  },
  {
    'id': 'taking_screenshots',
    'title': 'How do I take a screenshot?',
    'searchable_queries': [
      'screenshot',
      'how do I take a screenshot?',
      'how do I take a ss?',
      'ss?',
      'how do i screenshot it'
    ],
    'support_contents': 'Press the keyboard shortcut for your platform.\n\nWindows: `WINDOWS` + `SHIFT` + `S`\nMacOS: `COMMAND` + `SHIFT` + `4`\nLinux: `Print Screen`\n\nThen paste the image where you need it.'
  },
  {
    'id': 'enable_studio_access_to_api_services',
    'title': 'How do I enable Studio Access to API Services in my game?',
    'searchable_queries': [
      'studio access to api services',
      'studio access to api services',
      'enabling studio access to api services'
    ],
    'support_contents': 'Open the "Game Settings" menu in Roblox Studio, click on the "Security" tab, enable "Enable Studio Access to API Services", then save changes.'
  },
  {
    'id': 'product_testing',
    'title': 'Where can I test the products?',
    'searchable_queries': [
      'testing products',
      'testing game',
      'demo products',
      'demo game',
      'can you show me the products?',
      'can I test the products?',
      'how do I test the products?',
      'where can I test the products?',
      'where can I find the testing game?',
      'Where can I test the products before buying?',
      'how do I get in the testing game?',
      'where can I try out the products?',
      'where can I try out the lights?'
    ],
    'support_contents': 'Check out [Our Demo Game](https://demo.inertia.lighting/) to try out the products.'
  },
  {
    'id': 'better_graphics',
    'title': 'How do I make the lights look better?',
    'searchable_queries': [
      'Future Lighting',
      'How do I make the lights look better?',
      'How do I make my products look better?',
      'The lights don\'t look good in game.',
      'How do I get shadows to work?'
    ],
    'support_contents': '**There are a few ways that you can make your lights look better:**\n- Enable "Future Lighting"\n- Increase your "Graphics Quality"\n- Use a computer with a dedicated GPU\n- Don\'t use a mobile device\n\n**How do I enable Future Lighting?**\n1. Open your game in Roblox Studio.\n2. In the Explorer panel, click on "Lighting".\n3. In the Properties panel, click on "Technology".\n4. Select "Future".'
  },
  {
    'id': 'inertia_plus',
    'title': 'Inertia Plus',
    'searchable_queries': [
      'Inertia Plus',
      'Subscribe to Inertia.',
      'What is Inertia Plus?'
    ],
    'support_contents': '**What is it?**\nInertia Plus is a subscription service we offer which unlocks exclusive perks and features.\n\n**What are the benefits?**\n- You gain access to download and use all of our products. (*1)\n- You get to join in on all of the perks for our server boosters. (*2)\n\n**Will I lose my current products if I subscribe?**\nNo, you will retain your individually purchased licenses for our products.\n\n**Why should I subscribe?**\nIf you don\'t already own most of our products, Inertia Plus will allow you to download and use all of our products while subscribed.\n\n**Why should I not subscribe?**\nIf you already own most of our products, Inertia Plus probably isn\'t for you.\nThe main benefit of subscribing to Inertia Plus is to save money on using all of our products.\n\n**Where can I subscribe?**\nYou can subscribe [here](https://discord.com/channels/601889649601806336/role-subscriptions)\n\n`(*1)` You will retain previous purchases after your subscription has ended.\n`    ` Products transfers are not permitted while subscribed.\n`    ` \n`(*2)` Server booster perks will expire after your subscription has ended.'
  },
  {
    'id': 'disable_streaming_enabled',
    'title': 'How do I disable StreamingEnabled?',
    'searchable_queries': [
      'StreamingEnabled',
      'disable StreamingEnabled',
      'delete StreamingEnabled',
      'turn off StreamingEnabled',
      'how to disable StreamingEnabled',
      'how to delete StreamingEnabled',
      'how to turn off StreamingEnabled',
      'game.Workspace.StreamingEnabled'
    ],
    'support_contents': 'Our products weren\'t designed to work with `game.Workspace.StreamingEnabled` enabled.\n\nRoblox switched `game.Workspace.StreamingEnabled` to be enabled for all new experiences.\n\nWatch [this video](https://youtu.be/xApLkcuXwVk) to learn how to disable `game.Workspace.StreamingEnabled`.'
  },
  {
    'id': 'website_login',
    'title': 'I\'m having issues logging into the website',
    'searchable_queries': [
      'I can\'t login',
      'It wont let me login',
      'The website is broken for me',
      'Can’t login',
      'So I have an account but I cant login'
    ],
    'support_contents': 'There are a few things that you can try:\n- Make sure to login with the correct discord account\n- Try clearing your cache and cookies for the website'
  },
  {
    'id': 'how_to products',
    'title': 'How to use products',
    'searchable_queries': [
      'readme',
      'rtfm',
      'how do i use this product?',
      'how do i make groups'
    ],
    'support_contents': 'If you are having a problem with a product, consult the README in the product file before opening a ticket.'
  }
]