
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const AccountType = {
  roblox: 'roblox',
  discord: 'discord'
} as const

export type AccountType = (typeof AccountType)[keyof typeof AccountType]


export const PunishmentType = {
  warn: 'warn',
  kick: 'kick',
  ban: 'ban',
  blacklist: 'blacklist',
  mute: 'mute',
  timeout: 'timeout'
} as const

export type PunishmentType = (typeof PunishmentType)[keyof typeof PunishmentType]


export const TransactionType = {
  paypal: 'paypal',
  roblox: 'roblox',
  lumen: 'lumen',
  system: 'system'
} as const

export type TransactionType = (typeof TransactionType)[keyof typeof TransactionType]


export const GiftcardType = {
  product: 'product',
  balance: 'balance'
} as const

export type GiftcardType = (typeof GiftcardType)[keyof typeof GiftcardType]


export const TicketPriority = {
  low: 'low',
  medium: 'medium',
  high: 'high',
  onhold: 'onhold'
} as const

export type TicketPriority = (typeof TicketPriority)[keyof typeof TicketPriority]


export const IdType = {
  roblox: 'roblox',
  discord: 'discord',
  authentik: 'authentik'
} as const

export type IdType = (typeof IdType)[keyof typeof IdType]
