
name: "Full Build"

on:
  push:
    branches: [ master ]
  pull_request: {}

jobs:
    Build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [ 24.11.x ]
        steps:
        - name: Checkout repository
          uses: actions/checkout@v6
          with:
            token: ${{ secrets.INERTIA_TOKEN }}
            submodules: recursive
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v6
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
        - name: Use Latest Corepack
          run: |
            echo "Before: corepack version => $(corepack --version || echo 'not installed')"
            npm install -g corepack@latest
            echo "After : corepack version => $(corepack --version)"
            corepack enable
            pnpm --version
        - name: Install Dependencies
          run: pnpm install --ignore-scripts
        - name: Generate Prisma client
          run: pnpm build
          env: 
            DATABASE_URL: ${{ secrets.DATABASE_URL }}