name: "docker-cd"

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Build Docker Image
      #   run: |
      #     docker build . -t ci:0
          
      # - name: Deploy Docker
      #   run: |
      #     docker compose pull
