name: ESLint
on: [ push, pull_request, workflow_dispatch ]
jobs:
  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 23.x ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Yarn with Corepack
      run: corepack enable
    
    - name: Install Dependencies
      run: yarn

    - name: Run ESLint
      run: yarn lint
